INVALIDATE METADATA santander_business_risk_arda.contratos_morosidad_diaria_rda;
COMPUTE INCREMENTAL STATS santander_business_risk_arda.contratos_morosidad_diaria_rda;
INVALIDATE METADATA santander_business_risk_arda.contratos_morosidad_diaria_rda_inconsistencias;
COMPUTE INCREMENTAL STATS santander_business_risk_arda.contratos_morosidad_diaria_rda_inconsistencias;