CREATE VIEW IF NOT EXISTS bi_corp_business.vagg_pre_prestamos AS
select cod_per_nup as cod_nup,
sum(case when cod_prod_producto = '35' and cod_pre_situacionprestamo = '0' and cod_pre_situaciondeudaobjetiva <> '20' then 1 else 0 end) as int_prest_personal,
sum(case when cod_prod_producto = '35' and cod_pre_situacionprestamo = '0' and cod_pre_situaciondeudaobjetiva <> '20' and cod_div_divisa = 'ARS' then fc_pre_saldoreal else 0 end) as fc_prest_personal_pesos,
sum(case when cod_prod_producto = '35' and cod_pre_situacionprestamo = '0' and cod_pre_situaciondeudaobjetiva <> '20' and cod_div_divisa = 'USD' then fc_pre_saldoreal else 0 end) as fc_prest_personal_dolares,
sum(case when cod_prod_producto = '35' and cod_pre_productoactual = '70' then 1 else 0 end) as int_prest_personal_gym,
sum(case when cod_prod_producto = '35' and cod_pre_productoactual = '70' and cod_div_divisa = 'ARS' then fc_pre_saldoreal else 0 end) as fc_prest_personal_pesos_gym,
sum(case when cod_prod_producto = '35' and cod_pre_productoactual = '70' and cod_div_divisa = 'USD' then fc_pre_saldoreal else 0 end) as fc_prest_personal_dolares_gym,
sum(case when cod_prod_producto = '37' and cod_pre_situacionprestamo = '0' and cod_pre_situaciondeudaobjetiva <> '20' then 1 else 0 end) as int_prest_hipotecario,
sum(case when cod_prod_producto = '37' and cod_pre_situacionprestamo = '0' and cod_pre_situaciondeudaobjetiva <> '20' and cod_div_divisa = 'ARS' then fc_pre_saldoreal else 0 end) as fc_prest_hipotecario_pesos,
sum(case when cod_prod_producto = '37' and cod_pre_situacionprestamo = '0' and cod_pre_situaciondeudaobjetiva <> '20' and cod_div_divisa = 'USD' then fc_pre_saldoreal else 0 end) as fc_prest_hipotecario_dolares,
sum(case when cod_prod_producto = '37' and cod_pre_productoactual = '70' then 1 else 0 end) as int_prest_hipotecario_gym,
sum(case when cod_prod_producto = '37' and cod_pre_productoactual = '70' and cod_div_divisa = 'ARS' then fc_pre_saldoreal else 0 end) as fc_prest_hipotecario_pesos_gym,
sum(case when cod_prod_producto = '37' and cod_pre_productoactual = '70' and cod_div_divisa = 'USD' then fc_pre_saldoreal else 0 end) as fc_prest_hipotecario_dolares_gym,
sum(case when cod_prod_producto = '38' and cod_pre_situacionprestamo = '0' and cod_pre_situaciondeudaobjetiva <> '20' then 1 else 0 end) as int_prest_prendario,
sum(case when cod_prod_producto = '38' and cod_pre_situacionprestamo = '0' and cod_pre_situaciondeudaobjetiva <> '20' and cod_div_divisa = 'ARS' then fc_pre_saldoreal else 0 end) as fc_prest_prendario_pesos,
sum(case when cod_prod_producto = '38' and cod_pre_situacionprestamo = '0' and cod_pre_situaciondeudaobjetiva <> '20' and cod_div_divisa = 'USD' then fc_pre_saldoreal else 0 end) as fc_prest_prendario_dolares,
sum(case when cod_prod_producto = '38' and cod_pre_productoactual = '70' then 1 else 0 end) as int_prest_prendario_gym,
sum(case when cod_prod_producto = '38' and cod_pre_productoactual = '70' and cod_div_divisa = 'ARS' then fc_pre_saldoreal else 0 end) as fc_prest_prendario_pesos_gym,
sum(case when cod_prod_producto = '38' and cod_pre_productoactual = '70' and cod_div_divisa = 'USD' then fc_pre_saldoreal else 0 end) as fc_prest_prendario_dolares_gym,
sum(case when cod_prod_producto = '39' and cod_pre_situacionprestamo = '0' and cod_pre_situaciondeudaobjetiva <> '20' then 1 else 0 end) as int_prest_comercial,
sum(case when cod_prod_producto = '39' and cod_pre_situacionprestamo = '0' and cod_pre_situaciondeudaobjetiva <> '20' and cod_div_divisa = 'ARS' then fc_pre_saldoreal else 0 end) as fc_prest_comercial_pesos,
sum(case when cod_prod_producto = '39' and cod_pre_situacionprestamo = '0' and cod_pre_situaciondeudaobjetiva <> '20' and cod_div_divisa = 'USD' then fc_pre_saldoreal else 0 end) as fc_prest_comercial_dolares,
sum(case when cod_prod_producto = '39' and cod_pre_productoactual = '70' then 1 else 0 end) as int_prest_comercial_gym,
sum(case when cod_prod_producto = '39' and cod_pre_productoactual = '70' and cod_div_divisa = 'ARS' then fc_pre_saldoreal else 0 end) as fc_prest_comercial_pesos_gym,
sum(case when cod_prod_producto = '39' and cod_pre_productoactual = '70' and cod_div_divisa = 'USD' then fc_pre_saldoreal else 0 end) as fc_prest_comercial_dolares_gym,
sum(case when cod_prod_producto = '36' and cod_pre_situacionprestamo = '0' and cod_pre_situaciondeudaobjetiva <> '20' then 1 else 0 end) as int_prest_corporate,
sum(case when cod_prod_producto = '36' and cod_pre_situacionprestamo = '0' and cod_pre_situaciondeudaobjetiva <> '20' and cod_div_divisa = 'ARS' then fc_pre_saldoreal else 0 end) as fc_prest_corporate_pesos,
sum(case when cod_prod_producto = '36' and cod_pre_situacionprestamo = '0' and cod_pre_situaciondeudaobjetiva <> '20' and cod_div_divisa = 'USD' then fc_pre_saldoreal else 0 end) as fc_prest_corporate_dolares,
sum(case when cod_prod_producto = '36' and cod_pre_productoactual = '70' then 1 else 0 end) as int_prest_corporate_gym,
sum(case when cod_prod_producto = '36' and cod_pre_productoactual = '70' and cod_div_divisa = 'ARS' then fc_pre_saldoreal else 0 end) as fc_prest_corporate_pesos_gym,
sum(case when cod_prod_producto = '36' and cod_pre_productoactual = '70' and cod_div_divisa = 'USD' then fc_pre_saldoreal else 0 end) as fc_prest_corporate_dolares_gym,
sum(case when cod_prod_producto = '74' and cod_pre_situacionprestamo = '0' and cod_pre_situaciondeudaobjetiva <> '20' then 1 else 0 end) as int_prest_avales,
sum(case when cod_prod_producto = '74' and cod_pre_situacionprestamo = '0' and cod_pre_situaciondeudaobjetiva <> '20' and cod_div_divisa = 'ARS' then fc_pre_saldoreal else 0 end) as fc_prest_avales_pesos,
sum(case when cod_prod_producto = '74' and cod_pre_situacionprestamo = '0' and cod_pre_situaciondeudaobjetiva <> '20' and cod_div_divisa = 'USD' then fc_pre_saldoreal else 0 end) as fc_prest_avales_dolares,
sum(case when cod_prod_producto = '74' and cod_pre_productoactual = '70' then 1 else 0 end) as int_prest_avales_gym,
sum(case when cod_prod_producto = '74' and cod_pre_productoactual = '70' and cod_div_divisa = 'ARS' then fc_pre_saldoreal else 0 end) as fc_prest_avales_pesos_gym,
sum(case when cod_prod_producto = '74' and cod_pre_productoactual = '70' and cod_div_divisa = 'USD' then fc_pre_saldoreal else 0 end) as fc_prest_avales_dolares_gym,
sum(case when cod_prod_producto = '71' and cod_pre_situacionprestamo = '0' and cod_pre_situaciondeudaobjetiva <> '20' then 1 else 0 end) as int_prest_refinanciado,
sum(case when cod_prod_producto = '71' and cod_pre_situacionprestamo = '0' and cod_pre_situaciondeudaobjetiva <> '20' and cod_div_divisa = 'ARS' then fc_pre_saldoreal else 0 end) as fc_prest_refinanciado_pesos,
sum(case when cod_prod_producto = '71' and cod_pre_situacionprestamo = '0' and cod_pre_situaciondeudaobjetiva <> '20' and cod_div_divisa = 'USD' then fc_pre_saldoreal else 0 end) as fc_prest_refinanciado_dolares,
sum(case when cod_prod_producto = '71' and cod_pre_productoactual = '70' then 1 else 0 end) as int_prest_refinanciado_gym,
sum(case when cod_prod_producto = '71' and cod_pre_productoactual = '70' and cod_div_divisa = 'ARS' then fc_pre_saldoreal else 0 end) as fc_prest_refinanciado_pesos_gym,
sum(case when cod_prod_producto = '71' and cod_pre_productoactual = '70' and cod_div_divisa = 'USD' then fc_pre_saldoreal else 0 end) as fc_prest_refinanciado_dolares_gym,
partition_date
from bi_corp_common.stk_pre_prestamos
where partition_date='2021-05-18'
group by cod_per_nup, partition_date;