set hive.merge.mapfiles=true;
set hive.merge.mapredfiles=true;
set hive.merge.size.per.task=4000000;
set hive.merge.smallfiles.avgsize=16000000;
set hive.exec.dynamic.partition.mode=nonstrict;
set mapred.job.queue.name=root.dataeng;

INSERT OVERWRITE TABLE bi_corp_common.stk_adm_empresas_ficha_feve
    PARTITION (partition_date='{{ ti.xcom_pull(task_ids='InputConfig', key='partition_date', dag_id='LOAD_CMN_Admision_Empresas-Daily') }}')
SELECT
    cast(f.idfichafeve as int) id_adm_fichafeve,
    cast(f.nup as int) nt_adm_nup,
    f.razon_social as ds_adm_razon_social,
    cast(f.idsucursal as int) int_adm_idsucursal,
    f.supervision_riesgo ds_adm_supervision_riesgo,
    f.id_zona as id_adm_zona,
    cast(f.cuit as bigint) int_adm_cuit,
    f.grupo_economico as ds_adm_grupo_economico,
    f.gradofeve_origen as ds_adm_gradofeve_origen,
    f.gradofeve_actual as  ds_adm_gradofeve_actual,
    f.grado_feve_ficha as ds_adm_grado_feve_ficha,
    cast(f.importe_objetivo as decimal(16,2)) fc_adm_importe_objetivo,
    f.plazo_objetivo as ts_adm_plazo_objetivo,
    cast(f.tipo_comite as int) int_adm_tipo_comite,
    f.motivo_entrada as ds_adm_motivo_entrada,
    cast(f.calif_monto_disp as decimal(16,2)) fc_adm_calif_monto_disp,
    f.fecha_mensaje as ts_adm_fecha_mensaje,
    f.fecha_revision as ts_adm_fecha_revision,
    f.fecha_prox_revision as ts_adm_fecha_prox_revision,
    f.fecha_entrada as ts_adm_fecha_entrada,
    f.fecha_salida as ts_adm_fecha_salida,
    f.fecha_objetivo as ts_adm_fecha_objetivo,
    f.actividad_empresa as ds_adm_actividad_empresa,
    cast(f.calificacion as decimal(16,2)) dec_adm_calificacion,
    f.detalle_garantias as ds_adm_detalle_garantias,
    f.fecha_vencimiento as ts_adm_fecha_vencimiento,
    cast(f.valoracion_exp_pdm as decimal(16,2)) dec_adm_valoracion_exp_pdm,
    cast(f.valoracion_exp_accger as decimal(16,2)) dec_adm_valoracion_exp_accger,
    cast(f.valoracion_exp_acccred as decimal(16,2)) dec_adm_valoracion_exp_acccred,
    cast(f.valoracion_exp_rent as decimal(16,2)) dec_adm_valoracion_exp_rent,
    cast(f.valoracion_exp_gener as decimal(16,2)) dec_adm_valoracion_exp_gener,
    cast(f.valoracion_exp_solv as decimal(16,2)) dec_adm_valoracion_exp_solv,
    cast(f.valoracion_exp_porm as decimal(16,2)) dec_adm_valoracion_exp_porm,
    cast(f.valoracion_est_estadistico as decimal(16,2)) dec_adm_valoracion_est_estadistico,
    cast(f.valoracion_est_experto as decimal(16,2)) dec_adm_valoracion_est_experto,
    cast(f.valoracion_final as decimal(16,2)) dec_adm_valoracion_final,
    cast(f.activo_corriente_actual as decimal(16,2)) dec_adm_activo_corriente_actual,
    cast(f.activo_corriente_anterior as decimal(16,2)) dec_adm_activo_corriente_anterior,
    cast(f.activo_nocorriente_actual as decimal(16,2)) dec_adm_activo_nocorriente_actual,
    cast(f.activo_nocorriente_anterior as decimal(16,2)) dec_adm_activo_nocorriente_anterior,
    cast(f.total_activo_actual as decimal(16,2)) dec_adm_total_activo_actual,
    cast(f.total_activo_anterior as decimal(16,2)) dec_adm_total_activo_anterior,
    cast(f.pasivo_corriente_actual as decimal(16,2)) dec_adm_pasivo_corriente_actual,
    cast(f.pasivo_corriente_anterior as decimal(16,2)) dec_adm_pasivo_corriente_anterior,
    cast(f.deuda_bancaria_actual as decimal(16,2)) dec_adm_deuda_bancaria_actual,
    cast(f.deuda_bancaria_anterior as decimal(16,2)) dec_adm_deuda_bancaria_anterior,
    cast(f.total_pasivo_actual as decimal(16,2)) dec_adm_total_pasivo_actual,
    cast(f.total_pasivo_anterior as decimal(16,2)) dec_adm_total_pasivo_anterior,
    cast(f.patrimonio_neto_actual as decimal(16,2)) dec_adm_patrimonio_neto_actual,
    cast(f.patrimonio_neto_anterior as decimal(16,2)) dec_adm_patrimonio_neto_anterior,
    cast(f.ventas_actual as decimal(16,2)) dec_adm_ventas_actual,
    cast(f.ventas_anterior as decimal(16,2)) dec_adm_ventas_anterior,
    cast(f.resultado_operativo_actual as decimal(16,2)) dec_adm_resultado_operativo_actual,
    cast(f.resultado_operativo_anterior as decimal(16,2)) dec_adm_resultado_operativo_anterior,
    cast(f.resultado_neto_actual as decimal(16,2)) dec_adm_resultado_neto_actual,
    cast(f.resultado_neto_anterior as decimal(16,2)) dec_adm_resultado_neto_anterior,
    cast(f.generacion_propia_actual as decimal(16,2)) dec_adm_generacion_propia_actual,
    cast(f.generacion_propia_anterior as decimal(16,2)) dec_adm_generacion_propia_anterior,
    cast(f.liquidez_actual as decimal(16,2)) dec_adm_liquidez_actual,
    cast(f.liquidez_anterior as decimal(16,2)) dec_adm_liquidez_anterior,
    cast(f.endeudamiento as decimal(16,2)) dec_adm_endeudamiento,
    cast(f.ros as decimal(16,2)) dec_adm_ros,
    cast(f.deuda_bangen as decimal(16,2)) dec_adm_deuda_bangen,
    comentario_supervision as ds_adm_comentario_supervision,
    comentario_comite_anterior as ds_adm_comentario_comite_anterior,
    comentario_comite_actual as ds_adm_comentario_comite_actual,
    f.fecha_creacion as ts_adm_fecha_creacion,
    f.fecha_modificacion as ts_adm_fecha_modificacion,
    usuario_alta as ds_adm_usuario_alta,
    f.usuario_modificacion as ds_adm_usuario_modificacion,
    cast(f.estado as int) int_adm_estado,
    cast(f.meses as int) int_adm_meses,
    cast(f.importe as decimal(16,2)) fc_adm_importe,
    f.fecha_balance_anterior as ts_adm_fecha_balance_anterior,
    f.fecha_balance_actual as ts_adm_fecha_balance_actual,
    cast(f.porcentaje as decimal(16,2)) dec_adm_porcentaje,
    f.tipo_empresa as ds_adm_tipo_empresa,
    f.actividad_principal as ds_adm_actividad_principal,
    f.infopostbalance_mesanio as ds_adm_infopostbalance_mesanio,
    cast(f.nro_cliente as bigint) int_adm_nro_cliente,
    cast(f.total_ar as decimal (16,2)) dec_adm_total_ar,
    cast(f.total_us as decimal (16,2)) dec_adm_total_us,
    cast(f.total_grupo_ar as decimal (16,2)) dec_adm_total_grupo_ar,
    cast(f.total_grupo_us as decimal (16,2)) dec_adm_total_grupo_us,
    cast(f.deuda_ban_fin_corriente as decimal (16,2)) dec_adm_deuda_ban_fin_corriente,
    cast(f.deuda_ban_fin_no_corriente as decimal (16,2)) dec_adm_deuda_ban_fin_no_corriente,
    cast(f.ventas_netas as decimal (16,2)) dec_adm_ventas_netas,
    cast(f.endeudamiento_anterior as decimal (16,2)) dec_adm_endeudamiento_anterior,
    cast(f.ros_anterior as decimal (16,2)) dec_adm_ros_anterior,
    cast(f.deuda_bangen_anterior as decimal (16,2)) dec_adm_deuda_bangen_anterior,
    f.segmento as ds_adm_segmento,
    f.fecha_baja as ts_adm_fecha_baja,
    f.estadofeve as ds_adm_estadofeve,
    f.politica_seguir as ds_adm_politica_seguir,
    f.motivo_cambio_grado as ds_adm_motivo_cambio_grado,
    f.indice_cambio_grado as ds_adm_indice_cambio_grado,
    f.legajo as ds_adm_legajo,
    f.tipomensaje as ds_adm_tipomensaje,
    f.gestor as ds_adm_gestor,
    f.es_ultima_salida_feve as ds_adm_es_ultima_salida_feve,
    f.es_ultima_entrada_normal as ds_adm_es_ultima_entrada_normal,
    f.es_ultima_salida_automatica as ds_adm_es_ultima_salida_automatica,
    f.politica_seguir_bk as ds_adm_politica_seguir_bk
FROM bi_corp_staging.sge_feve_ficha f
WHERE partition_date='{{ ti.xcom_pull(task_ids='InputConfig', key='partition_date', dag_id='LOAD_CMN_Admision_Empresas-Daily') }}';
