INVALIDATE METADATA santander_business_risk_arda.contratos_rda;
COMPUTE INCREMENTAL STATS santander_business_risk_arda.contratos_rda;
INVALIDATE METADATA santander_business_risk_arda.contratos_rda_inconsistencias;
COMPUTE INCREMENTAL STATS santander_business_risk_arda.contratos_rda_inconsistencias;