set hive.merge.mapfiles=true;
set hive.merge.mapredfiles=true;
set hive.merge.size.per.task=4000000;
set hive.merge.smallfiles.avgsize=16000000;
set hive.exec.dynamic.partition.mode=nonstrict;
set mapred.job.queue.name=root.dataeng;

INSERT OVERWRITE TABLE bi_corp_common.stk_adm_empresas_omdm_cpp_propuesta
    PARTITION (partition_date='{{ ti.xcom_pull(task_ids='InputConfig', key='partition_date', dag_id='LOAD_CMN_Admision_OMDM_Empresas') }}')
select
    tipo_tramite as cod_adm_tipotramite,
    cod_tramite as cod_adm_tramite,
    substr(fec_proceso,1,19) as ts_adm_fecproceso,
    omdm.accionistaextrangero fla_adm_accionistaextrangero,
    omdm.aige cod_adm_aige,
    cast(omdm.antiguedadactividad as int) int_adm_antiguedadactividad,
    cast(omdm.antiguedadmaquinariamasnueva as int) int_adm_antiguedadmaquinariamasnueva,
    cast(omdm.antiguedadsociosenlaactividad as int) int_adm_antiguedadsociosenlaactividad,
    cast(omdm.arrendamientoagroncmra as double) fc_adm_arrendamientoagroncmra,
    cast(omdm.asistencialinea19prestagroga as double) fc_adm_asistencialinea19prestagroga,
    cast(omdm.asistencialinea63lineaagro as double) fc_adm_asistencialinea63lineaagro,
    omdm.cambiosenelpaqueteaccionario fla_adm_cambiosenelpaqueteaccionario,
    cast(omdm.cantbancosconlosqueopera as int) int_adm_cantbancosconlosqueopera,
    cast(omdm.cantclientes as int) int_adm_cantclientes,
    cast(omdm.cantdiasdesdeingresoamoria as int) int_adm_cantdiasdesdeingresoamoria,
    cast(omdm.cantempleados as int) int_adm_cantempleados,
    cast(omdm.cantentroenelciclo4 as int) int_adm_cantentroenelciclo4,
    cast(omdm.cantidaddechequesrechazadosnorescatadosult12meses as int) int_adm_cantidaddechequesrechazadosnorescatadosult12meses,
    cast(omdm.cantidaddechequesrechazadosrescatadosult12meses as int) int_adm_cantidaddechequesrechazadosrescatadosult12meses,
    cast(omdm.cantidaddediasatrasoenlatarjeta as int) int_adm_cantidaddediasatrasoenlatarjeta,
    cast(omdm.cantidaddediasdeatrasoenleasing as int) int_adm_cantidaddediasdeatrasoenleasing,
    cast(omdm.cantidaddediasdeatrasoenprestamos as int) int_adm_cantidaddediasdeatrasoenprestamos,
    cast(omdm.cantidaddediasexcedidoenlacuentacorriente as int) int_adm_cantidaddediasexcedidoenlacuentacorriente,
    cast(omdm.cantidadentroenelciclo1 as int) int_adm_cantidadentroenelciclo1,
    cast(omdm.cantidadentroenelciclo2 as int) int_adm_cantidadentroenelciclo2,
    cast(omdm.cantidadentroenelciclo3 as int) int_adm_cantidadentroenelciclo3,
    cast(omdm.cantidadmesesdesdelaultimapropuesta as int) int_adm_cantidadmesesdesdelaultimapropuesta,
    cast(omdm.cantingresosmoriasult12meses as int) int_adm_cantingresosmoriasult12meses,
    cast(omdm.cantlitroslechepordia as int) int_adm_cantlitroslechepordia,
    cast(omdm.cantmesesaltaaltair as int) int_adm_cantmesesaltaaltair,
    cast(omdm.cantmesesdesdealtaprimerproductoderiesgo as int) int_adm_cantmesesdesdealtaprimerproductoderiesgo,
    cast(omdm.cantmesesdesdelaultimaddjj as int) int_adm_cantmesesdesdelaultimaddjj,
    cast(omdm.cantmesesdesdeultimavisitaalaempresa as int) int_adm_cantmesesdesdeultimavisitaalaempresa,
    cast(omdm.cantrecondcerradasdosultanos as int) int_adm_cantrecondcerradasdosultanos,
    cast(omdm.cantrecondcerradasindepenfechacierre as int) int_adm_cantrecondcerradasindepenfechacierre,
    cast(omdm.cantrefiacuerdocerradosdosultanos as int) int_adm_cantrefiacuerdocerradosdosultanos,
    cast(omdm.cantrefiacuerdospagocerradosindependfechacierre as int) int_adm_cantrefiacuerdospagocerradosindependfechacierre,
    cast(omdm.cantsociosultimapropuestaaprobada as int) int_adm_cantsociosultimapropuestaaprobada,
    cast(omdm.cifrancmra as int) int_adm_cifrancmra,
    omdm.clasificacionmapariesgof485 cod_adm_clasificacionmapariesgof485,
    omdm.clienteengestionymora flag_adm_clienteengestionymora,
    cast(omdm.codigocampania as int) cod_adm_codigocampania,
    cast(omdm.codigosegmentosuc as int) cod_adm_codigosegmentosuc,
    cast(omdm.comprasganaderas as int) int_adm_comprasganaderas,
    cast(omdm.costodirectoagroncmra as double) fc_adm_costodirectoagroncmra,
    cast(omdm.costodirectoproduccion as double) fc_adm_costodirectoproduccion,
    cast(omdm.cuit as bigint) int_adm_cuit,
    omdm.cultivos desc_adm_cultivos,
    omdm.deudaprevisional flag_adm_deudaprevisional,
    cast(omdm.edadmayorsocio as int) int_adm_edadmayorsocio,
    cast(omdm.edadmenorsocio as int) int_adm_edadmenorsocio,
    omdm.eslasucursalmascercana flag_adm_eslasucursalmascercana,
    cast(omdm.exigiblebancario as double) fc_adm_exigiblebancario,
    omdm.experiencia cod_adm_experiencia,
    cast(omdm.facturacionagroncmra as double) fc_adm_facturacionagroncmra,
    cast(omdm.facturacionbrutatodoslosrubrospca as double) fc_adm_facturacionbrutatodoslosrubrospca,
    omdm.fechaconstitucion dt_adm_fechaconstitucion,
    omdm.fechapropuesta dt_adm_fechapropuesta,
    omdm.feve cod_adm_feve,
    omdm.fianzapersonalsocios flag_adm_fianzapersonalsocios,
    omdm.flujoomdm ds_adm_flujoomdm,
    cast(omdm.gastoscomercialesagroncmra as double) fc_adm_gastoscomercialesagroncmra,
    cast(omdm.gastoscomercializacionycosechas as double) fc_adm_gastoscomercializacionycosechas,
    cast(omdm.generaciondisponiblencmra as double) fc_adm_generaciondisponiblencmra,
    cast(omdm.generacionnetancmra as double) fc_adm_generacionnetancmra,
    cast(omdm.generacionpca as double) fc_adm_generacionpca,
    cast(omdm.generacionpcaanteultimoejercicio as double) fc_adm_generacionpcaanteultimoejercicio,
    omdm.lagerenciaesdiferentealosaccionistas flag_adm_lagerenciaesdiferentealosaccionistas,
    omdm.marcafianzapersonalsocios cod_adm_marcafianzapersonalsocios,
    omdm.marcafraudedomiciliolaboral flag_adm_marcafraudedomiciliolaboral,
    omdm.marcafraudeempresa flag_adm_marcafraudeempresa,
    omdm.marcafraudetelefonolaboral flag_adm_marcafraudetelefonolaboral,
    omdm.marcain00 cod_adm_marcain00,
    cast(omdm.montoacuerdocuentacorrientebsr as double) fc_adm_montoacuerdocuentacorrientebsr,
    cast(omdm.montodeexcesoenacc as double) fc_adm_montodeexcesoenacc,
    omdm.montofinal cod_adm_montofinal,
    omdm.montofinalsuc cod_adm_montofinalsuc,
    cast(omdm.montogarantia as double) fc_adm_montogarantia,
    cast(omdm.montoimpagodeleasing as double) fc_adm_montoimpagodeleasing,
    cast(omdm.montoimpagodeprestamos as double) fc_adm_montoimpagodeprestamos,
    cast(omdm.montopropuestasge as double) fc_adm_montopropuestasge,
    cast(omdm.montosolicitadolineasclean as double) fc_adm_montosolicitadolineasclean,
    omdm.nombrecliente ds_adm_nombrecliente,
    cast(omdm.numeropropuesta as int) int_adm_numeropropuesta,
    cast(omdm.nupcliente as int) int_adm_nupcliente,
    omdm.participanlossociosenotrasempresas flag_adm_participanlossociosenotrasempresas,
    cast(omdm.patrimonionetoganancias as double) fc_adm_patrimonionetoganancias,
    cast(omdm.pctestructsocietaria as double) int_adm_pctestructsocietaria,
    cast(omdm.pctparticipacionjovenes as double) int_adm_pctparticipacionjovenes,
    cast(omdm.pctparticipacionmayores70 as double) int_adm_pctparticipacionmayores70,
    cast(omdm.pctparticipacionmayorsocio as double) int_adm_pctparticipacionmayorsocio,
    cast(omdm.pctparticipacionmujerespaqueteaccionario as double) int_adm_pctparticipacionmujerespaqueteaccionario,
    omdm.perteneceacampania flag_adm_perteneceacampania,
    omdm.poseecosechadora cod_adm_poseecosechadora,
    omdm.poseegarantiareal flag_adm_poseegarantiareal,
    omdm.poseegarantiasliquidas flag_adm_poseegarantiasliquidas,
    omdm.poseereconduccionacuerdopagovig cod_adm_poseereconduccionacuerdopagovig,
    cast(omdm.saldoimpagodelatarjetadecredito as double) fc_adm_saldoimpagodelatarjetadecredito,
    omdm.segmentocomercialempresa cod_adm_segmentocomercialempresa,
    omdm.segmentoriesgoensuc cod_adm_segmentoriesgoensuc,
    cast(omdm.semaforoncmra as double) int_adm_semaforoncmra,
    cast(omdm.stockhacienda as int) int_adm_stockhacienda,
    cast(omdm.stocknovillos as int) int_adm_stocknovillos,
    cast(omdm.stockterneros as int) int_adm_stockterneros,
    cast(omdm.stockvacasenordene as int) int_adm_stockvacasenordene,
    cast(omdm.sucursalpropuesta as int) cod_adm_sucursalpropuesta,
    cast(omdm.sumasolvenciatotalsocios as double) fc_adm_sumasolvenciatotalsocios,
    cast(omdm.sumatotaldeudadeclarada as double) fc_adm_sumatotaldeudadeclarada,
    cast(omdm.sumatotaldeudainformadaenbcra as double) fc_adm_sumatotaldeudainformadaenbcra,
    cast(omdm.superficiealquiladaagriculturamasfrutales as int) int_adm_superficiealquiladaagriculturamasfrutales,
    cast(omdm.superficiealquiladacriainvernadatambo as int) int_adm_superficiealquiladacriainvernadatambo,
    cast(omdm.superficieaparceriaagriculturamasfrutales as int) int_adm_superficieaparceriaagriculturamasfrutales,
    cast(omdm.superficieaparceriacriainvernadatambo as int) int_adm_superficieaparceriacriainvernadatambo,
    cast(omdm.superficiepropiaagriculturamasfrutales as int) int_adm_superficiepropiaagriculturamasfrutales,
    cast(omdm.superficiepropiacriainvernadatambo as int) int_adm_superficiepropiacriainvernadatambo,
    omdm.tienesocios flag_adm_tienesocios,
    cast(omdm.tipocambio as double) fc_adm_tipocambio,
    cast(omdm.valoracionfinalempresa as double) fc_adm_valoracionfinalempresa,
    cast(omdm.valortierra as double) fc_adm_valortierra,
    cast(omdm.valorvehiculo as double) fc_adm_valorvehiculo,
    cast(omdm.ventasddjjganancias as double) fc_adm_ventasddjjganancias,
    omdm.zonacultivos desc_adm_zonacultivos,
    json as ds_adm_json
from bi_corp_staging.scoring_omdm_propuestas_empresas
lateral view json_tuple(json,
    'accionistaExtrangero',
    'aIGE',
    'antiguedadActividad',
    'antiguedadMaquinariaMasNueva',
    'antiguedadSociosEnLaActividad',
    'arrendamientoAgroNCMRA',
    'asistenciaLinea19PrestAgroGa',
    'asistenciaLinea63LineaAgro',
    'cambiosEnElPaqueteAccionario',
    'cantBancosConLosQueOpera',
    'cantClientes',
    'cantDiasDesdeIngresoAMoria',
    'cantEmpleados',
    'cantEntroEnElCiclo4',
    'cantidadDeChequesRechazadosNoRescatadosUlt12Meses',
    'cantidadDeChequesRechazadosRescatadosUlt12Meses',
    'cantidadDeDiasAtrasoEnLaTarjeta',
    'cantidadDeDiasDeAtrasoEnLeasing',
    'cantidadDeDiasDeAtrasoEnPrestamos',
    'cantidadDeDiasExcedidoEnLaCuentaCorriente',
    'cantidadEntroEnElCiclo1',
    'cantidadEntroEnElCiclo2',
    'cantidadEntroEnElCiclo3',
    'CantidadMesesDesdeLaUltimaPropuesta',
    'cantIngresosMoriasUlt12Meses',
    'cantLitrosLechePorDia',
    'cantMesesAltaAltair',
    'cantMesesDesdeAltaPrimerProductoDeRiesgo',
    'cantMesesDesdeLaUltimaDDJJ',
    'cantMesesDesdeUltimaVisitaALaEmpresa',
    'cantRecondCerradasDosUltAnos',
    'cantRecondCerradasIndepenFechaCierre',
    'cantRefiAcuerdoCerradosDosUltAnos',
    'cantRefiAcuerdosPagoCerradosIndependFechaCierre',
    'cantSociosUltimaPropuestaAprobada',
    'cifraNCMRA',
    'clasificacionMapaRiesgoF485',
    'clienteEnGestionYMora',
    'codigoCampania',
    'codigoSegmentoSUC',
    'comprasGanaderas',
    'costoDirectoAgroNCMRA',
    'costoDirectoProduccion',
    'CUIT',
    'cultivos',
    'deudaPrevisional',
    'edadMayorSocio',
    'edadMenorSocio',
    'esLaSucursalMasCercana',
    'exigibleBancario',
    'experiencia',
    'facturacionAgroNCMRA',
    'facturacionBrutaTodosLosRubrosPCA',
    'fechaConstitucion',
    'fechaPropuesta',
    'fEVE',
    'fianzaPersonalSocios',
    'flujoOMDM',
    'gastosComercialesAgroNCMRA',
    'gastosComercializacionYCosechas',
    'generacionDisponibleNCMRA',
    'generacionNetaNCMRA',
    'generacionPCA',
    'generacionPCAAnteultimoEjercicio',
    'laGerenciaEsDiferenteALosAccionistas',
    'marcaFianzaPersonalSocios',
    'marcaFraudeDomicilioLaboral',
    'marcaFraudeEmpresa',
    'marcaFraudeTelefonoLaboral',
    'marcaIN00',
    'montoAcuerdoCuentaCorrienteBSR',
    'montoDeExcesoEnACC',
    'montoFinal',
    'montoFinalSUC',
    'montoGarantia',
    'montoImpagoDeLeasing',
    'montoImpagoDePrestamos',
    'montoPropuestaSGE',
    'montoSolicitadoLineasClean',
    'nombreCliente',
    'numeroPropuesta',
    'NUPCliente',
    'participanLosSociosEnOtrasEmpresas',
    'patrimonioNetoGanancias',
    'pctEstructSocietaria',
    'pctParticipacionJovenes',
    'pctParticipacionMayores70',
    'pctParticipacionMayorSocio',
    'pctParticipacionMujeresPaqueteAccionario',
    'perteneceACampania',
    'poseeCosechadora',
    'poseeGarantiaReal',
    'poseeGarantiasLiquidas',
    'poseeReconduccionAcuerdoPagoVig',
    'saldoImpagoDeLaTarjetaDeCredito',
    'segmentoComercialEmpresa',
    'segmentoRiesgoEnSUC',
    'semaforoNCMRA',
    'stockHacienda',
    'stockNovillos',
    'stockTerneros',
    'stockVacasEnOrdene',
    'sucursalPropuesta',
    'sumaSolvenciaTotalSocios',
    'sumaTotalDeudaDeclarada',
    'sumaTotalDeudaInformadaEnBCRA',
    'superficieAlquiladaAgriculturaMasFrutales',
    'superficieAlquiladaCriaInvernadaTambo',
    'superficieAparceriaAgriculturaMasFrutales',
    'superficieAparceriaCriaInvernadaTambo',
    'superficiePropiaAgriculturaMasFrutales',
    'superficiePropiaCriaInvernadaTambo',
    'tieneSocios',
    'tipoCambio',
    'valoracionFinalEmpresa',
    'valorTierra',
    'valorVehiculo',
    'ventasDDJJGanancias',
    'zonaCultivos'
) omdm as
    accionistaExtrangero,
    aIGE,
    antiguedadActividad,
    antiguedadMaquinariaMasNueva,
    antiguedadSociosEnLaActividad,
    arrendamientoAgroNCMRA,
    asistenciaLinea19PrestAgroGa,
    asistenciaLinea63LineaAgro,
    cambiosEnElPaqueteAccionario,
    cantBancosConLosQueOpera,
    cantClientes,
    cantDiasDesdeIngresoAMoria,
    cantEmpleados,
    cantEntroEnElCiclo4,
    cantidadDeChequesRechazadosNoRescatadosUlt12Meses,
    cantidadDeChequesRechazadosRescatadosUlt12Meses,
    cantidadDeDiasAtrasoEnLaTarjeta,
    cantidadDeDiasDeAtrasoEnLeasing,
    cantidadDeDiasDeAtrasoEnPrestamos,
    cantidadDeDiasExcedidoEnLaCuentaCorriente,
    cantidadEntroEnElCiclo1,
    cantidadEntroEnElCiclo2,
    cantidadEntroEnElCiclo3,
    CantidadMesesDesdeLaUltimaPropuesta,
    cantIngresosMoriasUlt12Meses,
    cantLitrosLechePorDia,
    cantMesesAltaAltair,
    cantMesesDesdeAltaPrimerProductoDeRiesgo,
    cantMesesDesdeLaUltimaDDJJ,
    cantMesesDesdeUltimaVisitaALaEmpresa,
    cantRecondCerradasDosUltAnos,
    cantRecondCerradasIndepenFechaCierre,
    cantRefiAcuerdoCerradosDosUltAnos,
    cantRefiAcuerdosPagoCerradosIndependFechaCierre,
    cantSociosUltimaPropuestaAprobada,
    cifraNCMRA,
    clasificacionMapaRiesgoF485,
    clienteEnGestionYMora,
    codigoCampania,
    codigoSegmentoSUC,
    comprasGanaderas,
    costoDirectoAgroNCMRA,
    costoDirectoProduccion,
    CUIT,
    cultivos,
    deudaPrevisional,
    edadMayorSocio,
    edadMenorSocio,
    esLaSucursalMasCercana,
    exigibleBancario,
    experiencia,
    facturacionAgroNCMRA,
    facturacionBrutaTodosLosRubrosPCA,
    fechaConstitucion,
    fechaPropuesta,
    fEVE,
    fianzaPersonalSocios,
    flujoOMDM,
    gastosComercialesAgroNCMRA,
    gastosComercializacionYCosechas,
    generacionDisponibleNCMRA,
    generacionNetaNCMRA,
    generacionPCA,
    generacionPCAAnteultimoEjercicio,
    laGerenciaEsDiferenteALosAccionistas,
    marcaFianzaPersonalSocios,
    marcaFraudeDomicilioLaboral,
    marcaFraudeEmpresa,
    marcaFraudeTelefonoLaboral,
    marcaIN00,
    montoAcuerdoCuentaCorrienteBSR,
    montoDeExcesoEnACC,
    montoFinal,
    montoFinalSUC,
    montoGarantia,
    montoImpagoDeLeasing,
    montoImpagoDePrestamos,
    montoPropuestaSGE,
    montoSolicitadoLineasClean,
    nombreCliente,
    numeroPropuesta,
    NUPCliente,
    participanLosSociosEnOtrasEmpresas,
    patrimonioNetoGanancias,
    pctEstructSocietaria,
    pctParticipacionJovenes,
    pctParticipacionMayores70,
    pctParticipacionMayorSocio,
    pctParticipacionMujeresPaqueteAccionario,
    perteneceACampania,
    poseeCosechadora,
    poseeGarantiaReal,
    poseeGarantiasLiquidas,
    poseeReconduccionAcuerdoPagoVig,
    saldoImpagoDeLaTarjetaDeCredito,
    segmentoComercialEmpresa,
    segmentoRiesgoEnSUC,
    semaforoNCMRA,
    stockHacienda,
    stockNovillos,
    stockTerneros,
    stockVacasEnOrdene,
    sucursalPropuesta,
    sumaSolvenciaTotalSocios,
    sumaTotalDeudaDeclarada,
    sumaTotalDeudaInformadaEnBCRA,
    superficieAlquiladaAgriculturaMasFrutales,
    superficieAlquiladaCriaInvernadaTambo,
    superficieAparceriaAgriculturaMasFrutales,
    superficieAparceriaCriaInvernadaTambo,
    superficiePropiaAgriculturaMasFrutales,
    superficiePropiaCriaInvernadaTambo,
    tieneSocios,
    tipoCambio,
    valoracionFinalEmpresa,
    valorTierra,
    valorVehiculo,
    ventasDDJJGanancias,
    zonaCultivos
where partition_date = '{{ ti.xcom_pull(task_ids='InputConfig', key='partition_date', dag_id='LOAD_CMN_Admision_OMDM_Empresas') }}' and label = 'propuesta';