CREATE TABLE VTADIR01.BA_EQUIPOS_TAS (
	ID_EQUIPO NUMBER,
	BILLETE_MIN VARCHAR2(10),
	HDDH VARCHAR2(7),
	HHDH VARCHAR2(7),
	TAS_PRISMA VARCHAR2(2),
	UBICACION VARCHAR2(10),
	SUC_CC VARCHAR2(3),
	TAS_PRISMA_F DATE
);