CREATE TABLE GEC01.GC_TIPO_RECLAMO_ESPANA (
	COD_ENTIDAD CHAR(4),
	COD_TIPO_RECLAMO NUMBER(3,0),
	DESC_TIPO_RECLAMO VARCHAR2(255),
	USER_ALT VARCHAR2(8) DEFAULT 'VINICIAL'            ,
	FEC_ALT DATE DEFAULT SYSDATE               ,
	USER_MODF VARCHAR2(8) DEFAULT 'VINICIAL'            ,
	FEC_MODF DATE DEFAULT SYSDATE               ,
	ESTADO VARCHAR2(1) DEFAULT 'A');