INVALIDATE METADATA santander_business_risk_arda.reclamaciones_incidencias_rda;
COMPUTE INCREMENTAL STATS santander_business_risk_arda.reclamaciones_incidencias_rda;
INVALIDATE METADATA santander_business_risk_arda.reclamaciones_incidencias_rda_inconsistencias;
COMPUTE INCREMENTAL STATS santander_business_risk_arda.reclamaciones_incidencias_rda_inconsistencias;