
-- ENC_ESTADO
-- MOTIVO_VISITA_V2
-- SUCURSALES
-- SUCURSALRIO
-- ENC_PUESTO_CITAS 
-- ENC_TURNO
-- ENC_DURACION

SELECT * FROM CITAS.ENC_ESTADO WHERE ROWNUM <= 10 ; -- ID_ESTADO,DESCRI | sin campo novedad
SELECT * FROM CITAS.MOTIVO_VISITA_V2 WHERE ROWNUM <= 10 ; -- | sin campo novedad
SELECT * FROM CITAS.SUCURSALES WHERE ROWNUM <= 10 ; -- | ALTA_TEC
SELECT * FROM CITAS.SUCURSALRIO WHERE ROWNUM <= 10 ; -- | sin campo novedad
SELECT * FROM CITAS.ENC_PUESTO_CITAS WHERE ROWNUM <= 10 ; -- | sin campo novedad

SELECT * FROM CITAS.ENC_DURACION WHERE ROWNUM <= 10 ;
SELECT * FROM CITAS.ENC_TURNO WHERE ROWNUM <= 10 ;
SELECT * FROM CITAS.ENC_TIPO_TURNO WHERE ROWNUM <= 10 ;

SELECT COUNT(1) FROM CITAS.ENC_TURNO WHERE TO_CHAR(FECHA_DESDE) = '2020-12-05'
------------------------------------------------------------------------------
SELECT * FROM CITAS.SECTOR

SELECT * FROM CITAS.ENC_TURNO WHERE NUP IS NOT NULL
 
SELECT * FROM CITAS.ENC_ESTADO WHERE CITAS.ENC_ESTADO_EJECUTIVO

SELECT * FROM CITAS.ENC_LOG_ENCOLADOR_WEB

SELECT * FROM CITAS.ENC_ATENCION_TURNO

SELECT * FROM CITAS.ENC_TURNO_CAN

SELECT MIN(FECHA_DESDE), MAX(FECHA_DESDE) FROM CITAS.ENC_TURNO

SELECT * FROM CITAS.ENC_TIPO_TURNO


SELECT * FROM CITAS.ENC_TURNO_HIST 

SELECT DISTINCT SUBSTR(FECHA_HORA_DESDE , 1, 6) FROM CITAS.ENC_TURNO_HIST ORDER BY 1; 

SELECT DISTINCT SUBSTR(FECHA_HORA_DESDE , 1, 6) FROM CITAS.ENC_TURNO_HIST_BACKUP ORDER BY 1; 