
--******* TABLAS CALCULADOR
SELECT * FROM TBL_CALCULADOR_BENEFICIO ;
SELECT COUNT(1) FROM TBL_CALCULADOR_BENEFICIO ; -- 400

SELECT * FROM TBL_CALCULADOR_CATALOGO ;
SELECT COUNT(1) FROM TBL_CALCULADOR_CATALOGO ; --103

SELECT * FROM TBL_CALCULADOR_CONDICION ;
SELECT COUNT(1) FROM TBL_CALCULADOR_CONDICION ; --256

SELECT * FROM TBL_CALCULADOR_DETALLE ;
SELECT COUNT(1) FROM TBL_CALCULADOR_DETALLE ; --159

SELECT * FROM TBL_CALCULADOR_PROGRAMA_VENTA ;
SELECT COUNT(1) FROM TBL_CALCULADOR_PROGRAMA_VENTA ; --70

SELECT * FROM TBL_CALCULADOR_PROMOCION ;
SELECT COUNT(1) FROM TBL_CALCULADOR_PROMOCION ; --1521

SELECT * FROM TBL_CALCULADOR_REGLA ;
SELECT COUNT(1) FROM TBL_CALCULADOR_REGLA ; --718

SELECT * FROM TBL_CALCULADOR_REQUISITO ;
SELECT COUNT(1) FROM TBL_CALCULADOR_REQUISITO ; --66


--******* TABLAS MI EQUIPIO Y EQUIPO_PUESTO
SELECT * FROM TBL_MI_EQUIPO ;
SELECT COUNT(1) FROM TBL_MI_EQUIPO ; --5031

SELECT * FROM TBL_MI_EQUIPO_ERM ;
SELECT COUNT(1) FROM TBL_MI_EQUIPO_ERM ; --456

SELECT * FROM TBL_MI_EQUIPO_HIST_ERM ;
SELECT COUNT(1) FROM TBL_MI_EQUIPO_HIST_ERM ; --2286

SELECT * FROM TBL_MI_EQUIPO_PUESTO ;
SELECT COUNT(1) FROM TBL_MI_EQUIPO_PUESTO ; --10019


--__/__/__/__/__/__/__/__/__/__/__/__/__/__/__/__/__/

SELECT CD_CANAL_VENTA, DS_CANAL_VENTA, MC_ACTIVO
FROM MKT02.TBL_CANAL_VENTA;

SELECT CD_CANAL_COMUNICACION, DS_CANAL_COMUNICACION
FROM MKT02.TBL_CANAL_COMUNICACION;

--SELECT CD_INTERACCION, NRO_TICKET
--FROM MKT02.TBL_TICKET_INTERACCION;

SELECT CD_INTERACCION, NRO_TICKET
FROM MKT02.TBL_TICKET_INTERACCION;


--__/__/__/__/__/__/__/__/__/__/__/__/__/__/__/__/__/

SELECT SUBSTR2(TO_CHAR(DT_INICIO), 4, 6) FROM MKT02.TBL_INTERACCION -- HIST 2018-05-26 11:06:49

SELECT SUBSTR2(TO_CHAR(DT_INICIO), 4, 6) DT_INICIO
	, count(distinct NUP) clientes
FROM MKT02.TBL_INTERACCION_HIST
WHERE SUBSTR2(TO_CHAR(DT_INICIO), 4, 6) = ('FEB-21')
GROUP BY SUBSTR2(TO_CHAR(DT_INICIO), 4, 6) ;

SELECT * FROM MKT02.TBL_INTERACCION

SELECT * FROM MKT02.GESTION WHERE CODIGO = 722

SELECT SUBSTR2(TO_CHAR(DT_INICIO), 4, 6) DT_INICIO
	, count(distinct NUP) clientes
FROM MKT02.TBL_INTERACCION_HIST
WHERE SUBSTR2(TO_CHAR(DT_INICIO), 4, 6) = ('DEC-20')
GROUP BY SUBSTR2(TO_CHAR(DT_INICIO), 4, 6) ;

SELECT TO_CHAR(DT_INICIO, 'YYYY-MM-DD') DT_INITCIO , COUNT(DISTINCT NUP) Q 
FROM MKT02.TBL_INTERACCION_HIST WHERE TO_CHAR(DT_INICIO, 'YYYY-MM') IN ('2020-10','2020-11','2020-12')
GROUP BY TO_CHAR(DT_INICIO, 'YYYY-MM-DD') ;




SELECT TO_CHAR(DT_MODIFICACION , 'YYYY-MM-DD') , COUNT(DISTINCT CD_INTERACCION)
FROM MKT02.TBL_INTERACCION_PRODUCTO_HIST WHERE TO_CHAR(DT_MODIFICACION , 'YYYY-MM') IN ('2020-10','2020-11','2020-12')
GROUP BY TO_CHAR(DT_MODIFICACION , 'YYYY-MM-DD') ;


SELECT
	A.CD_GESTION ,
	A.CD_RESULTADO ,
	A.CD_IDENTIFICACION_RESULTADO ,
	B.DESCRIPCION
FROM
	MKT02.TBL_INTERACCION_PRODUCTO A
LEFT JOIN MKT02.TBL_MOTIVO_ESTADO B 
	ON B.CODIGO = A.CD_RESULTADO

--where partition_Date >= '2021-02-15';
 SELECT
	CD_GESTION ,
	CD_RESULTADO 
	CD_IDENTIFICACION_RESULTADO 
FROM
	MKT02.TBL_INTERACCION_ALERTA
--where partition_Date >= '2021-02-15';

SELECT * FROM MKT02.TBL_TICKET_INTERACCION

SELECT * FROM MKT02.TBL_GESTION_PRODUCTO

SELECT * FROM MKT02.TBL_MOTIVO_ESTADO

SELECT * FROM MKT02.TBL_MOTIVO_ESTADO

SELECT * FROM MKT02.TIPOGESTION

SELECT * FROM MKT02.TBL_COMBO_IATX_TMK WHERE CAMPO1 = '78';



--tbl_interaccion_alerta:
--cd_alerta --> Codigos de alerta. Los valores mayores que 1601 vienen de GALA. Son alertas UPBC. Los demás son códigos de alerta generados en masche. Ver enum de códigos de alerta *1
--cd_resultado --> Resultado de la gestion CAMPO CODIGO  de la tabla tbl_combo_iatx_tmk. Ver valores de enum CodigoGesion *2
--cd_gestion   --> Hacer la búsqueda sobre el CAMPO1  de la tabla tbl_combo_iatx_tmk para ver las descripciones
--Tiene seteados valores hardcode en el SP PKG_CLIENT_SERVICES.setAlertData_v3 dependiendo del campo CD_RESULTADO: DECODE(p_cd_estado,  1, 722,  2, 16,  3, 999,  0)

--tbl_interaccion_producto:
--cd_escenario --> No esta clara la utilización de este campo.
--cd_gestion --> Hacer la busqueda sobre el CAMPO1  de la tabla tbl_combo_iatx_tmk para ver las descripciones
--cd_resultado --> Resultado de la gestion CAMPO CODIGO  de la tabla tbl_combo_iatx_tmk.
--cd_identificacion_resultado --> Resultado de la gestion, CAMPO3   de la tabla tbl_combo_iatx_tmk.
--cd_producto_crm --> Se puede ver la descripcion en el campo DS_PRODUCTO_CRM de la tabla TBL_INTERACCION_PRODUCTO












SELECT COUNT(1) FROM MKT02.TBL_COMBO_IATX_TMK ;
