SELECT
	decode(max(USER_ID), NULL, 'FALSE', 'TRUE') BOOL_VAL
FROM
	USER_TABLE
WHERE
	USER_ID = [SOME USER_ID here]
	
--__/__/__/__/__/__/__/__/__/__/__/__/__/__/__/__/__/__/__/
/*	
SELECT FEC_DATA PARTITION_DATE
	, COD_ESTADO_PLANIFICACION ESTADO
	, TO_CHAR(FEC_FIN_EJEC, 'YYYY-MM-DD') DATE_LOAD_COMPLETE
	, TO_CHAR(FEC_FIN_EJEC, 'DAY') DAY_LOAD
	, TO_CHAR(FEC_FIN_EJEC, 'hh24:mm') END_TIME
	, CASE WHEN TO_CHAR(FEC_FIN_EJEC, 'hh24:mm') > '11:30' OR CAST(TO_CHAR(FEC_FIN_EJEC, 'YYYYMMDD') AS INT) - FEC_DATA > 2 THEN 1 ELSE 0 END OFF_PLANIF
FROM
	mismtd.MS0_DT_PLANNING
WHERE cod_planificacion = 'BATCH_D' AND 
	fec_data >= '20210101'  
	AND cod_estado_planificacion = 'F'
	AND cod_entorno = '54' 
ORDER BY 1 DESC ; 
*/
	

SELECT CASE WHEN FEC_FIN_EJEC IS NULL THEN 0 ELSE 1 END BOOL_TRIGGER, FEC_DATA, FEC_FIN_EJEC 
FROM MISMTD.MS0_DT_PLANNING WHERE COD_PLANIFICACION = 'BATCH_D' 
AND TO_CHAR(FEC_FIN_EJEC, 'YYYY-MM-DD') = TO_CHAR(SYSDATE , 'YYYY-MM-DD') AND COD_ENTORNO = '54' ;


SELECT MAX(FEC_DATA) FROM MISMTD.MS0_DT_PLANNING WHERE COD_PLANIFICACION = 'BATCH_D' AND COD_ESTADO_PLANIFICACION = 'F' AND COD_ENTORNO = '54'

