CREATE TABLE CITAS.ENC_TURNO_EXT (
	ID_TURNO NUMBER(10,0),
	ID_CANAL NUMBER(4,0),
	FECHA_ALTA DATE,
	NOTIFICACION NUMBER(4,0),
	EJECUTIVO_ROL VARCHAR2(20),
	COMENTARIO_CLIENTE VARCHAR2(200) DEFAULT NULL
);