CREATE TABLE CITAS.ENC_ESTADO (
	ID_ESTADO NUMBER(10,0),
	DESCRI VARCHAR2(50),
	CONSTRAINT SYS_C0010408 PRIMARY KEY (ID_ESTADO)
);
CREATE UNIQUE INDEX SYS_C0010408 ON CITAS.ENC_ESTADO (ID_ESTADO);