-- CITAS.ENC_DURACION definition

-- DDL generated by DBeaver
-- WARNING: It may differ from actual native database DDL

-- Drop table

-- DROP TABLE CITAS.ENC_DURACION;

CREATE TABLE CITAS.ENC_DURACION (
	ID_DURACION NUMBER(10,0),
	DURACION NUMBER(4,0),
	SECTOR VARCHAR2(1),
	ID_TIPO_TURNO NUMBER(10,0)
);