CREATE TABLE CRMBE.SUCURSALES (
	SUCU_ID NUMBER DEFAULT "CRMBE"."ISEQ$$_73983".nextval,
	CANT_DEPOSITO_ATM NUMBER(10,0),
	CANT_SERVICIOS_ATM NUMBER(10,0),
	CANT_EXTRACCION_ATM NUMBER(10,0),
	DIRECCION_ID NUMBER(10,0),
	REF_LEGACY VARCHAR2(9),
	SUCU_NOMBRE VARCHAR2(100),
	HABILITADO NUMBER(1,0) );