INVALIDATE METADATA santander_business_risk_arda.clientes_rda;
COMPUTE INCREMENTAL STATS santander_business_risk_arda.clientes_rda;
INVALIDATE METADATA santander_business_risk_arda.clientes_rda_inconsistencias;
COMPUTE INCREMENTAL STATS santander_business_risk_arda.clientes_rda_inconsistencias;