INVALIDATE METADATA santander_business_risk_arda.portafolio_curva_sens_rda;
COMPUTE INCREMENTAL STATS santander_business_risk_arda.portafolio_curva_sens_rda;
INVALIDATE METADATA santander_business_risk_arda.portafolio_curva_sens_rda_inconsistencias;
COMPUTE INCREMENTAL STATS santander_business_risk_arda.portafolio_curva_sens_rda_inconsistencias;