spk_master: yarn

query_raw_data: '/santander/bi-corp/sandbox/bi/config/seguros/queries/query_raw_input_data.hql'

db_name: analytics

tbl_name: mm_predict_seguros_auto

pipeline: '/santander/bi-corp/sandbox/bi/config/seguros/modelos/pipeline_auto.pkl'

model: '/santander/bi-corp/sandbox/bi/config/seguros/modelos/Model_auto.pkl'

model_cols: '/santander/bi-corp/sandbox/bi/config/seguros/modelos/Model_cols_auto.pkl'