spk_master: yarn

query_raw_data: '/aplicaciones/bi/zonda/repositories/zonda-etl/scripts/analytics/queries/query_raw_input_data.hql'

db_name: analytics

tbl_name: mm_predict_seguros_vivienda

pipeline: '/santander/bi-corp/sandbox/bi/config/seguros/modelos/pipeline_vivienda.pkl'

model: '/santander/bi-corp/sandbox/bi/config/seguros/modelos/Model_vivienda.pkl'

model_cols: '/santander/bi-corp/sandbox/bi/config/seguros/modelos/Model_cols_vivienda.pkl'