query_cli: '/santander/bi-corp/sandbox/bi/config/seguros/queries/query_test_clientes.hql'
query_emp: '/santander/bi-corp/sandbox/bi/config/seguros/queries/query_empleado.hql'
query_domicilio: '/santander/bi-corp/sandbox/bi/config/seguros/queries/query_domicilios.hql'
query_mora: '/santander/bi-corp/sandbox/bi/config/seguros/queries/query_contratos_mora.hql'
query_cotizaciones: '/santander/bi-corp/sandbox/bi/config/seguros/queries/query_cotizaciones.hql'
query_persona: '/santander/bi-corp/sandbox/bi/config/seguros/queries/query_persona.hql'
query_cons_rub: '/santander/bi-corp/sandbox/bi/config/seguros/queries/query_consumos_rubros.hql'
params_ora: '/santander/bi-corp/sandbox/bi/config/seguros/params_raw_input.json'
db_ora_30: RIO30
db_ora_61: SRV_RIO61_AP
db_name: analytics
tbl_name: mm_raw_input_model_seguros