INVALIDATE METADATA santander_business_risk_arda.especies_basico_rda;
COMPUTE INCREMENTAL STATS santander_business_risk_arda.especies_basico_rda;
INVALIDATE METADATA santander_business_risk_arda.especies_basico_rda_inconsistencias;
COMPUTE INCREMENTAL STATS santander_business_risk_arda.especies_basico_rda_inconsistencias;