INVALIDATE METADATA santander_business_risk_arda.empleado_formacion_rda;
COMPUTE INCREMENTAL STATS santander_business_risk_arda.empleado_formacion_rda;
INVALIDATE METADATA santander_business_risk_arda.empleado_formacion_rda_inconsistencias;
COMPUTE INCREMENTAL STATS santander_business_risk_arda.empleado_formacion_rda_inconsistencias;