CREATE TABLE CSM.USUARIOS (
	ID_USUARIO VARCHAR2(8),
	APELLIDO VARCHAR2(40),
	NOMBRE VARCHAR2(40),
	EMAIL VARCHAR2(100),
	GUID_TIBCO VARCHAR2(36),
	ID_USUARIO_ALTA VARCHAR2(8),
	FECHA_ALTA DATE,
	FECHA_BAJA DATE,
	ID_USUARIO_MODIF VARCHAR2(8),
	FECHA_MODIF DATE,
	COD_SUCURSAL VARCHAR2(3),
	COD_OFICINA VARCHAR2(3))