CREATE TABLE CSM.TIPOS_GESTION (
	ID_TIPO_GESTION NUMBER(1,0),
	DESC_TIPO_GESTION VARCHAR2(30),
	ID_USUARIO_ALTA VARCHAR2(8),
	FECHA_ALTA DATE,
	FECHA_BAJA DATE,
	ID_USUARIO_MODIF VARCHAR2(8),
	FECHA_MODIF DATE,
	INFORMA_BCRA VARCHAR2(1),
	PREFIJO_TICKET VARCHAR2(2),
	ID_TIPOS_GESTION_SGC NUMBER(1,0))