CREATE TABLE CSM.GEST_RESOL_ACCIONES (
	ID_GESTION NUMBER(9,0),
	ID_ACCION NUMBER(6,0),
	IND_ORIGEN CHAR(1),
	ID_USUARIO_ALTA VARCHAR2(8),
	FECHA_ALTA DATE,
	FECHA_BAJA DATE,
	ID_USUARIO_MODIF VARCHAR2(8),
	FECHA_MODIF DATE,
	IND_EJECUCION CHAR(1))