CREATE TABLE CSM.CODIGOS_OPERATIVOS_TARJETA (
	COD_OPERATIVO VARCHAR2(10),
	DESC_MOVIMIENTO VARCHAR2(30),
	IND_PAGO_TARJETA VARCHAR2(1),
	ID_USUARIO_ALTA VARCHAR2(8),
	FECHA_ALTA DATE,
	ID_USUARIO_MODIF VARCHAR2(8),
	FECHA_MODIF DATE,
	FECHA_BAJA DATE,
	COD_AJUSTE VARCHAR2(4),
	COD_SUBAJUSTE VARCHAR2(4))