CREATE TABLE CSM.CODIGOS_OPERATIVOS_CUENTA (
	COD_OPERATIVO VARCHAR2(4),
	DESC_CORTA VARCHAR2(14),
	DESC_LARGA VARCHAR2(34),
	COD_ANULACION VARCHAR2(4),
	CLASIF_MOV VARCHAR2(6),
	COD_CONCEPTO_BRIO VARCHAR2(4),
	ID_USUARIO_ALTA VARCHAR2(8),
	FECHA_ALTA DATE,
	ID_USUARIO_MODIF VARCHAR2(8),
	FECHA_MODIF DATE,
	FECHA_BAJA DATE,
	TIPO_DESTINO VARCHAR2(2))