CREATE TABLE CSM.GEST_MOTDES_ACCIONES (
	ID_GESTION NUMBER(9,0),
	ID_ACCION NUMBER(6,0),
	VALOR_ACCION VARCHAR2(100),
	COD_GRUPO NUMBER(1,0),
	ID_USUARIO_ALTA VARCHAR2(8),
	FECHA_ALTA DATE,
	ID_USUARIO_MODIF VARCHAR2(8),
	FECHA_MODIF DATE,
	FECHA_BAJA DATE,
	IND_ORIGEN VARCHAR2(1))