CREATE TABLE CSM.CASUISTICA_MOTIVOS (
	ID_CASUISTICA NUMBER(6,0),
	COD_MOTIVO NUMBER(2,0),
	DESC_MOTIVO VARCHAR2(60),
	IND_TEXTO_LIBRE CHAR(1),
	ID_USUARIO_ALTA VARCHAR2(8),
	FECHA_ALTA DATE,
	ID_USUARIO_MODIF VARCHAR2(8),
	FECHA_MODIF DATE,
	FECHA_BAJA DATE,
	ID_MOTIVO NUMBER(16,0),
	ID_TIPO_GESTION NUMBER(1,0))