CREATE TABLE CSM.MOTDES_ARBOL_RESULTADOS (
	ID_CASUISTICA NUMBER(6,0),
	COD_RESULTADO NUMBER(3,0),
	DESC_RESULTADO VARCHAR2(50),
	TEXTO_MENSAJE VARCHAR2(2000),
	IND_FAVORABILIDAD CHAR(1),
	ID_USUARIO_ALTA VARCHAR2(8),
	FECHA_ALTA DATE,
	ID_USUARIO_MODIF VARCHAR2(8),
	FECHA_MODIF DATE,
	FECHA_BAJA DATE)