CREATE TABLE CSM.CANALES (
	ID_CANAL NUMBER(16,0),
	COD_CANAL VARCHAR2(8),
	DESC_CANAL VARCHAR2(90),
	ID_USUARIO_ALTA VARCHAR2(8),
	FECHA_ALTA DATE,
	ID_USUARIO_MODIF VARCHAR2(8),
	FECHA_MODIF DATE,
	FECHA_BAJA DATE)