CREATE TABLE GEC01.CIRCUITO
(
  COD_ENTIDAD               CHAR(4 BYTE)        NOT NULL,
  IDE_CIRCUITO              NUMBER(5)           NOT NULL,
  COD_CIRCUITO              NUMBER(5)           NOT NULL,
  FEC_VIG_DDE_CIRC          DATE                NOT NULL,
  FEC_VIG_HTA_CIRC          DATE                NOT NULL,
  DESC_CIRC                 VARCHAR2(1000 BYTE),
  DESC_DETALL_CIRC          VARCHAR2(1000 BYTE),
  TPO_GESTION               NUMBER(4)           NOT NULL,
  COD_PROD                  NUMBER(4)           NOT NULL,
  COD_SUBPROD               NUMBER(4)           NOT NULL,
  COD_CPTO                  NUMBER(4)           NOT NULL,
  COD_SUBCPTO               NUMBER(4)           NOT NULL,
  TMP_ASIGN_ESPECIAL        NUMBER(4)           NOT NULL,
  TMP_PEDIDO_INFO           NUMBER(4)           NOT NULL,
  TMP_CIRC                  NUMBER(6)           NOT NULL,
  INDI_GEST_PEND            CHAR(1 BYTE)        NOT NULL,
  INDI_MAIL_DEMORA          CHAR(1 BYTE)        NOT NULL,
  INDI_CIERR_AUTM           CHAR(1 BYTE)        NOT NULL,
  INDI_AUTORIZA_ITEM        CHAR(1 BYTE)        NOT NULL,
  COD_RECIBO                NUMBER(5)           NOT NULL,
  EST_CIRC                  CHAR(1 BYTE)        NOT NULL,
  USER_ALT_CIRC             VARCHAR2(8 BYTE)    NOT NULL,
  FEC_ALT_CIRC              DATE                NOT NULL,
  USER_MODF_CIRC            VARCHAR2(8 BYTE)    NOT NULL,
  FEC_MODF_CIRC             DATE                NOT NULL,
  INDI_MODIF_DATOS          CHAR(1 BYTE)        DEFAULT 0                     NOT NULL,
  INDI_RECEP_RESP           CHAR(1 BYTE)        DEFAULT NULL                  NOT NULL,
  INDI_SUCURSALES           CHAR(1 BYTE)        NOT NULL,
  INDI_DEJAR_PEND           CHAR(1 BYTE)        DEFAULT 'O'                   NOT NULL,
  COD_TPO_RESOL             CHAR(1 BYTE)        DEFAULT 'F',
  UND_TIEMPO                CHAR(1 BYTE)        DEFAULT 'D',
  TPO_VIS_GEST              CHAR(1 BYTE)        DEFAULT 'T'                   NOT NULL,
  INDI_SUMA_TMP_AUTZ        CHAR(1 BYTE)        DEFAULT 'N'                   NOT NULL,
  COD_CONFORME              NUMBER(5)           DEFAULT 0                     NOT NULL,
  INDI_JERARQUIA_AUTZ       CHAR(1 BYTE)        DEFAULT 'N'                   NOT NULL,
  INDI_SECUENCIA_AUTZ       CHAR(1 BYTE)        DEFAULT 'N'                   NOT NULL,
  INDI_ASIG_PARALELO        CHAR(1 BYTE)        DEFAULT 'N'                   NOT NULL,
  INDI_AUTORIZ_DEVOL        CHAR(1 BYTE)        DEFAULT 'N'                   NOT NULL,
  INDI_MODF_FEC             CHAR(1 BYTE)        DEFAULT 'N'                   NOT NULL,
  CIRCUITO_PREDECESOR       NUMBER(5),
  INDI_CRIT                 CHAR(1 BYTE)        DEFAULT 'N'                   NOT NULL,
  INDI_INFO_MULTIVALUADA    CHAR(1 BYTE)        DEFAULT 'S'                   NOT NULL,
  INDI_ENVIAR_MAIL_RECEP    CHAR(1 BYTE),
  INDI_ENVIAR_SMS_RECEP     CHAR(1 BYTE),
  INDI_ENVIAR_MAIL_RESP     CHAR(1 BYTE),
  INDI_ENVIAR_SMS_RESP      CHAR(1 BYTE),
  INDI_ENVIAR_MAIL_DEMORA   CHAR(1 BYTE),
  COD_MODELO_MSJ            NUMBER(2),
  ID_CLASIF_SELECT          INTEGER             DEFAULT 2                     NOT NULL,
  ID_PARRAFO_CUERPO_MAIL    INTEGER,
  INDI_USO_MONTO            CHAR(1 BYTE)        DEFAULT 'N'                   NOT NULL,
  INDI_ENVIAR_CARTA_RESP    CHAR(1 BYTE)        DEFAULT 'N'                   NOT NULL,
  COD_COMPROBANTE_CLIENTE   NUMBER,
  INDI_ENVIAR_MAIL_PROV     CHAR(1 BYTE),
  INDI_REAPERTURA           CHAR(1 BYTE)        DEFAULT 'R',
  LONG_COMENTARIO_RECEP     NUMBER              DEFAULT 4000,
  LONG_COMENTARIO_CLIENTE   NUMBER              DEFAULT 3000,
  AVISO_VENC_GEST           NUMBER(2),
  INDI_ENVIAR_MAIL_NO_AUTZ  CHAR(1 BYTE)        DEFAULT 'N',
  COD_ENTIDAD_AFECT         NUMBER              DEFAULT 1                     NOT NULL
);