CREATE TABLE GEC01.GC_EMPRESAS
(
  COD_ENTIDAD            CHAR(4 BYTE)           NOT NULL,
  TPO_DOC_EMPR           CHAR(1 BYTE)           NOT NULL,
  NRO_DOC_EMPR           NUMBER(11)             NOT NULL,
  SEC_DOC_EMPR           NUMBER(2)              NOT NULL,
  TPO_EMPR               CHAR(4 BYTE),
  FEC_INI_ACTIV_EMPR     DATE                   NOT NULL,
  COD_ACTIV_EMPR         CHAR(3 BYTE)           NOT NULL,
  NOM_COMER_EMPR         VARCHAR2(100 BYTE)     NOT NULL,
  RAZON_SOCIAL_EMPR      VARCHAR2(100 BYTE)     NOT NULL,
  IDE_NUP_EMPR           CHAR(8 BYTE)           DEFAULT 0                     NOT NULL,
  APE_RESP_EMPR          VARCHAR2(30 BYTE)      NOT NULL,
  NOM_RESP_EMPR          VARCHAR2(30 BYTE)      NOT NULL,
  TPO_DOC2_EMPR          CHAR(1 BYTE),
  NRO_DOC2_EMPR          NUMBER(11)             DEFAULT 0                     NOT NULL,
  COD_SUC_EMPR           NUMBER(4),
  COD_SEGM_EMPR          CHAR(3 BYTE)           NOT NULL,
  COD_CRM_EMPR           VARCHAR2(2 BYTE)       NOT NULL,
  SEMF_INGRESO_CRM       CHAR(2 BYTE),
  SEMF_RENTA_CRM         CHAR(2 BYTE),
  SEMF_RIESGO_CRM        CHAR(4 BYTE),
  RENTABILIDAD_PROMEDIO  NUMBER(14,2),
  COLOR_SEMAFORO         CHAR(1 BYTE),
  COLOR_SEMAF_RIESGO     VARCHAR2(2 BYTE)
)