CREATE TABLE GEC01.GC_GESTIONES
(
  COD_ENTIDAD               CHAR(4 BYTE)        NOT NULL,
  IDE_GESTION_SECTOR        CHAR(4 BYTE)        NOT NULL,
  IDE_GESTION_NRO           NUMBER(8)           NOT NULL,
  COD_SEGM                  CHAR(3 BYTE)        NOT NULL,
  SEMF_INGRESO_CRM          VARCHAR2(2 BYTE),
  SEMF_RENTA_CRM            VARCHAR2(2 BYTE),
  SEMF_RIESGO_CRM           CHAR(4 BYTE),
  CALLE_DOM_CONTC           VARCHAR2(50 BYTE),
  NRO_DOM_CONTC             NUMBER(5)           DEFAULT 0                     NOT NULL,
  PISO_DOM_CONTC            CHAR(2 BYTE),
  DPTO_DOM_CONTC            CHAR(4 BYTE),
  CPOST_DOM_CONTC           CHAR(8 BYTE),
  LOC_DOM_CONTC             VARCHAR2(50 BYTE),
  PCIA_DOM_CONTC            NUMBER(2)           DEFAULT 0,
  PAIS_DOM_CONTC            CHAR(3 BYTE),
  DDN_TEL_DOM_CONTC         NUMBER(6)           DEFAULT 0                     NOT NULL,
  NRO_TEL_DOM_CONTC         NUMBER(15)          DEFAULT 0                     NOT NULL,
  DDN_FAX_CONTC             NUMBER(6)           DEFAULT 0                     NOT NULL,
  NRO_FAX_CONTC             NUMBER(15)          DEFAULT 0                     NOT NULL,
  HRA_DOM_CONTC             VARCHAR2(100 BYTE),
  DDN_CELULAR_CONTC         NUMBER(6)           DEFAULT 0                     NOT NULL,
  NRO_CELULAR_CONTC         NUMBER(15)          DEFAULT 0                     NOT NULL,
  DDN_TEL_LABORAL           NUMBER(6)           DEFAULT 0                     NOT NULL,
  NRO_TEL_LABORAL           NUMBER(15)          DEFAULT 0                     NOT NULL,
  HRA_TEL_LABORAL           VARCHAR2(100 BYTE),
  DDN_FAX_LABORAL           NUMBER(6)           DEFAULT 0                     NOT NULL,
  NRO_FAX_LABORAL           NUMBER(15)          DEFAULT 0                     NOT NULL,
  APLIC_CTA                 CHAR(4 BYTE),
  COD_SUC_CTA               NUMBER(3),
  NRO_CTA                   NUMBER(16)          DEFAULT 0                     NOT NULL,
  NRO_FIRM_CTA              NUMBER(5)           DEFAULT 0                     NOT NULL,
  COD_MONE_CTA              CHAR(3 BYTE),
  COD_PROD_CTA              CHAR(2 BYTE),
  COD_SUBPRO_CTA            CHAR(4 BYTE),
  NRO_TARJETA               NUMBER(20)          DEFAULT 0                     NOT NULL,
  LINK_RESUMEN              VARCHAR2(200 BYTE),
  DIRE_MAIL_CONTC           VARCHAR2(100 BYTE),
  DIRE_MAIL2_CONTC          VARCHAR2(100 BYTE),
  CARTERA                   NUMBER(2),
  APLIC_CTA_GOLD            CHAR(4 BYTE),
  COD_SUC_CTA_GOLD          NUMBER(3),
  NRO_CTA_GOLD              NUMBER(16),
  NRO_FIRM_CTA_GOLD         NUMBER(5),
  COD_MONE_CTA_GOLD         CHAR(3 BYTE),
  COD_PROD_CTA_GOLD         CHAR(2 BYTE),
  COD_SUBPRO_CTA_GOLD       CHAR(4 BYTE),
  COD_RAMO_CTA              NUMBER(2),
  NRO_CERTIFICADO_CTA       NUMBER(9),
  RENTABILIDAD_PROMEDIO     NUMBER(14,2),
  COLOR_SEMAFORO            CHAR(1 BYTE),
  COLOR_SEMAF_RIESGO        VARCHAR2(2 BYTE),
  INDI_ENVIOS_MYA           NUMBER(2),
  DIRE_MAIL_OPCIONAL        VARCHAR2(100 BYTE),
  NRO_PAQUETE               NUMBER(20),
  COD_PAQUETE               NUMBER(4),
  INDI_PLAN_SUELDO          CHAR(1 BYTE),
  NRO_CONVENIO_PAQUETE      VARCHAR2(7 BYTE),
  EMP_CELULAR_CONTC         CHAR(4 BYTE),
  TPO_MSJ_ASOC_RTA          NUMBER(5),
  MONTO_DEUDA_REF           NUMBER(14,3)        DEFAULT NULL,
  NO_ENVIAR_NOTIFICACIONES  CHAR(1 BYTE),
  ID_EJECUTIVO              VARCHAR2(50 BYTE)   DEFAULT NULL
)