CREATE TABLE GEC01.GESTIONES
(
  COD_ENTIDAD             CHAR(4 BYTE)          NOT NULL,
  IDE_GESTION_SECTOR      CHAR(4 BYTE)          NOT NULL,
  IDE_GESTION_NRO         NUMBER(8)             NOT NULL,
  IDE_CIRCUITO            NUMBER(5)             NOT NULL,
  INDI_TIPO_CIRC          CHAR(1 BYTE)          DEFAULT 0                     NOT NULL,
  INDI_DECISION_COMER     CHAR(1 BYTE)          DEFAULT 'N'                   NOT NULL,
  INDI_REPLTEO            CHAR(1 BYTE)          DEFAULT 'N'                   NOT NULL,
  INDI_RTA_INMED          CHAR(1 BYTE)          NOT NULL,
  INDI_IMPRE_CART         CHAR(1 BYTE),
  IMP_AUTZ_SOLICITADO     NUMBER(13,2)          DEFAULT 0                     NOT NULL,
  COD_MONE_SOLICITADO     CHAR(3 BYTE),
  IMP_AUTZ_AUTORIZADO     NUMBER(13,2)          DEFAULT 0                     NOT NULL,
  COD_MONE_AUTORIZADO     CHAR(3 BYTE),
  IMP_AUTZ_RESOLUCION     NUMBER(13,2)          DEFAULT 0                     NOT NULL,
  COD_MONE_RESOLUCION     CHAR(3 BYTE),
  TPO_PERS                CHAR(1 BYTE)          NOT NULL,
  COD_CRM                 VARCHAR2(2 BYTE)      NOT NULL,
  COMEN_CLIENTE           VARCHAR2(4000 BYTE),
  IDE_GEST_SECTOR_RELAC   CHAR(6 BYTE),
  IDE_GEST_NRO_RELAC      NUMBER(8),
  FEC_GESTION_ALTA        DATE,
  COD_BANDEJA_ACTUAL      VARCHAR2(30 BYTE),
  FEC_BANDEJA_ACTUAL      DATE,
  COD_SECTOR_ACTUAL       CHAR(4 BYTE),
  INIC_USER_ALTA          CHAR(5 BYTE)          DEFAULT 'NNNNN'               NOT NULL,
  INDI_MAIL               CHAR(1 BYTE),
  INDI_PRIORIDAD          NUMBER(5)             DEFAULT 0                     NOT NULL,
  FEC_MAX_RESOL           DATE                  DEFAULT SYSDATE,
  COD_CONFORME            NUMBER(5)             DEFAULT 0                     NOT NULL,
  COD_USER_ACTUAL         VARCHAR2(8 BYTE),
  COD_GRUPO_EMPRESA       NUMBER(1)             DEFAULT 2                     NOT NULL,
  COD_TIPO_FAVORABILIDAD  NUMBER(2),
  FEC_AVISO_VENC          DATE
)