CREATE TABLE GEC01.INFORMACION_ADJUNTA
(
  COD_ENTIDAD           CHAR(4 BYTE)            NOT NULL,
  IDE_GESTION_SECTOR    CHAR(4 BYTE)            NOT NULL,
  IDE_GESTION_NRO       NUMBER(8)               NOT NULL,
  COD_ACTOR             NUMBER(2)               NOT NULL,
  NRO_ORDEN             NUMBER(5)               NOT NULL,
  INDI_TPO_INFO         NUMBER(1)               NOT NULL,
  COD_INFO_DOC_REQUE    NUMBER(5)               NOT NULL,
  DATO_INFO_DOC_REQUE   VARCHAR2(2000 BYTE),
  LINK_INF_ADJUNTA      VARCHAR2(200 BYTE),
  FEC_INF_ADJUNTA       DATE                    NOT NULL,
  USER_INF_ADJUNTA      VARCHAR2(50 BYTE)       NOT NULL,
  COD_SECT_INF_ADJUNTA  CHAR(4 BYTE),
  NOM_ARCHIVO_ORIGINAL  VARCHAR2(100 BYTE),
  NOM_ARCHIVO           VARCHAR2(100 BYTE),
  NOM_DIRECTORIO        VARCHAR2(100 BYTE),
  TAMANO                NUMBER,
  SECUENCIA             NUMBER(2)               DEFAULT 0                     NOT NULL
)