CREATE TABLE GEC01.SECTORES
(
  COD_ENTIDAD            CHAR(4 BYTE)           NOT NULL,
  COD_SECTOR             CHAR(4 BYTE)           NOT NULL,
  DESC_SECT              VARCHAR2(200 BYTE)     NOT NULL,
  COD_GRUPO              CHAR(4 BYTE)           NOT NULL,
  INDI_ACTRAL            CHAR(1 BYTE)           NOT NULL,
  COD_PCIA               NUMBER(2)              NOT NULL,
  MAIL_SECTOR            VARCHAR2(80 BYTE),
  EST_SECT               CHAR(1 BYTE)           NOT NULL,
  USER_ALT_SECT          VARCHAR2(8 BYTE)       NOT NULL,
  FEC_ALT_SECT           DATE                   NOT NULL,
  USER_MODF_SECT         VARCHAR2(8 BYTE)       NOT NULL,
  FEC_MODF_SECT          DATE                   NOT NULL,
  ENVIAR_MAIL            CHAR(1 BYTE)           DEFAULT 'S'                   NOT NULL,
  INDI_INFO_ASIG_ESP     CHAR(1 BYTE)           DEFAULT 'S'                   NOT NULL,
  COD_PAIS               CHAR(3 BYTE)           NOT NULL,
  INDI_RESOL_INFO_ADJ    CHAR(1 BYTE)           DEFAULT 'N'                   NOT NULL,
  COD_CTRO_COSTOS        VARCHAR2(10 BYTE),
  INDI_MAIL_BANDEJA      CHAR(1 BYTE)           DEFAULT 'N',
  INDI_USO_CARTA         CHAR(1 BYTE)           DEFAULT 'N'                   NOT NULL,
  SECTOR_OWNER           CHAR(4 BYTE)           NOT NULL,
  COD_GRUPO_EMPRESA      NUMBER(1)              DEFAULT 2,
  INDI_ADMIN             CHAR(1 BYTE)           DEFAULT 'N'                   NOT NULL,
  GEST_X_PAG_BANDEJA     NUMBER(4)              DEFAULT 20                    NOT NULL,
  COD_SUCURSAL           NUMBER(4),
  COD_ZONA               CHAR(4 BYTE),
  TIPO_SECTOR            NUMBER(4)              NOT NULL,
  CLASS_PDF              VARCHAR2(255 BYTE),
  DIAS_GESTIONES_ANT     NUMBER(4),
  COD_SECTOR_GEN         CHAR(4 BYTE),
  INDI_COMPROMISO_GOLD   CHAR(1 BYTE)           DEFAULT 'N'                   NOT NULL,
  INDI_ENVIAR_MAIL_RESP  CHAR(1 BYTE),
  INDI_ENVIAR_SMS_RESP   CHAR(1 BYTE),
  INDI_NO_ENVIAR_MYA     CHAR(1 BYTE)           DEFAULT 'N',
  INDI_INSTANCIAS_POST   CHAR(1 BYTE)           DEFAULT 'N'
)