CREATE TABLE GEC01.SUBCONCEPTO
(
  COD_ENTIDAD          CHAR(4 BYTE)             NOT NULL,
  COD_SUBCPTO          NUMBER(4)                NOT NULL,
  DESC_SUBCPTO         VARCHAR2(80 BYTE)        NOT NULL,
  DESC_DETALL_SUBCPTO  VARCHAR2(1000 BYTE),
  EST_SUBCPTO          CHAR(1 BYTE)             NOT NULL,
  USER_ALT_SUBCPTO     VARCHAR2(8 BYTE)         NOT NULL,
  FEC_ALT_SUBCPTO      DATE                     NOT NULL,
  USER_MODF_SUBCPTO    VARCHAR2(8 BYTE)         NOT NULL,
  FEC_MODF_SUBCPTO     DATE                     NOT NULL,
  SECTOR_OWNER         CHAR(4 BYTE)             NOT NULL
)