CREATE TABLE GEC01.TIPO_GESTION
(
  COD_ENTIDAD           CHAR(4 BYTE)            NOT NULL,
  TPO_GESTION           NUMBER(4)               NOT NULL,
  DESC_TPO_GEST         VARCHAR2(50 BYTE)       NOT NULL,
  DESC_DETALL_TPO_GEST  VARCHAR2(1000 BYTE)     NOT NULL,
  EST_TPO_GEST          CHAR(1 BYTE)            NOT NULL,
  USER_ALT_TPO_GEST     VARCHAR2(8 BYTE)        NOT NULL,
  FEC_ALT_TPO_GEST      DATE                    NOT NULL,
  USER_MODF_TPO_GEST    VARCHAR2(8 BYTE)        NOT NULL,
  FEC_MODF_TPO_GEST     DATE                    NOT NULL
)