SET mapred.job.queue.name=root.dataeng;
SELECT concat_ws(',',coalesce(cast(s02.s02_nro_tarjeta as string),''),
coalesce(cast(s02.s02_rel_aplicacion as string),''),
coalesce(cast(s02.s02_rel_cod_suc as string),''),
coalesce(cast(s02.s02_rel_tipo_cta as string),''),
coalesce(cast(s02.s02_rel_nro_cta as string),''),
coalesce(cast(s02.s02_rel_nro_firm as string),''),
coalesce(cast(s02.s02_tipo_cuenta as string),''),
coalesce(cast(s02.s02_cuenta_tc as string),''),
coalesce(cast(s02.s02_cod_sucursal as string),''),
coalesce(cast(s02.s02_estado_tarjeta as string),''),
coalesce(cast(s02.s02_fecha_alta as string),''),
coalesce(cast(s02.s02_motivo_alta as string),''),
coalesce(cast(s02.s02_nro_solicitud as string),''),
coalesce(cast(s02.s02_campania_id as string),''),
coalesce(cast(s02.s02_campania_nro_shot as string),''),
coalesce(cast(s02.s02_vig_des_aa as string),''),
coalesce(cast(s02.s02_vig_des_mm as string),''),
coalesce(cast(s02.s02_vig_has_aa as string),''),
coalesce(cast(s02.s02_vig_has_mm as string),''),
coalesce(cast(s02.s02_ult_modif_fec as string),''),
coalesce(cast(s02.s02_ult_modif_orig as string),''),
coalesce(cast(s02.s02_ult_modif_hora as string),''),
coalesce(cast(s02.s02_ult_modif_userid as string),''),
coalesce(cast(s02.s02_tipo_tarjeta as string),''),
coalesce(cast(s02.s02_marca_women as string),''),
coalesce(cast(s02.s02_no_renov_motivo as string),''),
coalesce(cast(s02.s02_no_renov_fecha as string),''),
coalesce(cast(s02.s02_fec_baja as string),''),
coalesce(cast(s02.s02_motivo_baja as string),''),
coalesce(cast(s02.s02_nro_cta_emp as string),''),
coalesce(cast(s02.s02_mca_habilit as string),''),
coalesce(cast(s02.s02_mca_cargo as string),''),
coalesce(cast(s02.s02_apel_nomb_emb as string),''),
coalesce(cast(s02.s02_cod_categoria as string),''),
coalesce(cast(s02.s02_fec_incl_boletin as string),''),
coalesce(cast(s02.s02_motivo_incl_boletin as string),''),
coalesce(cast(s02.s02_userid_alta as string),''),
coalesce(cast(s02.s02_canal_vta as string),''),
coalesce(cast(s02.s02_autorizado_tc as string),''),
coalesce(cast(s02.s02_marca_tc as string),''),
coalesce(cast(s02.s02_cargo as string),''),
coalesce(cast(s02.s02_bonificacion as string),''),
coalesce(cast(s02.s02_cuotas as string),''),
coalesce(cast(s02.s02_linea4 as string),''),
coalesce(cast(s02.s02_lim_compras as string),''),
coalesce(cast(s02.s02_lim_cuotas as string),''),
coalesce(cast(s02.s02_lim_adelantos as string),''),
coalesce(cast(s02.s02_estado_activacion as string),''),
coalesce(cast(s02.s02_nro_tarjeta_relac as string),''),
coalesce(cast(s02.s02_fecha_actual_women as string),''),
coalesce(cast(p08.penumper as string),'')) AS line
FROM bi_corp_staging.amas_wamas02 s02
LEFT JOIN bi_corp_staging.malpe_pedt008 p08 ON p08.penumcon = coalesce(cast(s02.s02_rel_nro_cta as string),'') AND REGEXP_REPLACE(p08.pecodofi, "^0+", '') = coalesce(cast(s02.s02_rel_cod_suc as string),'') AND REGEXP_REPLACE(p08.peordpar, "^0+", '') = coalesce(cast(s02.s02_rel_nro_firm as string),'') and s02.partition_date=p08.partition_date
WHERE s02.partition_date='$partition_date'
AND (p08.partition_date='$partition_date' or p08.partition_date is null);
