SELECT M.NUP, M.MAQ_ID, TO_CHAR(M.FECHA,'DD/MM/YYYY') FECHA, M.HORA, M.TIPO_CLIENTE, M.SUC_NRO,
              M.SUC_MAQ, M.TX_ID, M.ORIG_REV, M.USUARIO, M.CUADRANTE,
              M.IMPORTE, M.MONEDA, M.CANTIDAD_CHEQUES, M.PESUBSEG, M.CANTIDAD_EFECTIVO, M.IMPORTE_EFECTIVO,
              M.IMPORTE_CHEQUES, M.CANTIDAD_OTROS, M.IMPORTE_OTROS, M.MEDIO_PAGO
FROM CNL01.MOVIMIENTO m, 
          CNL01.AGRUPAMIENTO a
WHERE a.COD_SECTOR = 'CG'
    AND a.CANAL_ID = 'CAJA'
    AND a.TX_ID = m.TX_ID
    AND m.CANAL_ID = a.CANAL_ID
    AND m.FECHA >= '01-AGO-2020'
    AND m.FECHA <= '31-AGO-2020'
    AND m.MAQ_ID BETWEEN '8000' AND '8099'
    AND m.SUC_MAQ = '492'
ORDER BY m.SUC_MAQ, m.MAQ_ID, m.FECHA, m.HORA 