INVALIDATE METADATA santander_business_risk_arda.expediente_rda;
COMPUTE INCREMENTAL STATS santander_business_risk_arda.expediente_rda;
INVALIDATE METADATA santander_business_risk_arda.expediente_rda_inconsistencias;
COMPUTE INCREMENTAL STATS santander_business_risk_arda.expediente_rda_inconsistencias;