-- CASOS QUE GC02 NO SE ACTUALIZA:

-- no está el tipo medio COSMOS
SELECT * FROM GEC01.TIPO_MEDIOS 
WHERE TPO_MEDIO NOT IN (
SELECT TME_COD FROM GEC02.DIM_TIPO_MEDIOS)

-- no esta el sector PPN1
SELECT * FROM GEC01.SECTORES 
WHERE cod_sector NOT IN (
SELECT sec_cod FROM GEC02.DIM_SECTORES)


