
-- __/__/__/__/__/__/__/__/__/__/__/__/__/__/__/__/__/__/__/__/__/__/__/__/__ROF_modificado.

--FEC_DATA|COD_CONTENIDO|ROF       |
----------|-------------|----------|
--20200630|CTB          |   -816.45|
--20200630|CTB          |40621.6802|
--20200630|CCL          |94947.7999|

-- COUNT(IDF_CTO_ODS): 1.767

SELECT BWHCORE.MS0_FT_DWH_BLCE_RESULT.FEC_DATA,
	BWHCORE.MS0_FT_DWH_BLCE_RESULT.COD_CONTENIDO,
	--BWHCORE.MS0_FT_DWH_BLCE_RESULT.COD_AREA_NEGOCIO,
	--BWHCORE.MS0_FT_DWH_BLCE_RESULT.COD_DIVISA,
	--BWHCORE.MS0_DM_DWH_CTA_RESULTADOS_CTR.COD_CTA_RESULTADOS_NIV_7,
	--BWHCORE.MS0_DM_DWH_CTA_RESULTADOS_CTR.COD_CTA_RESULTADOS_NIV_8,
	sum(nvl(BWHCORE.MS0_FT_DWH_BLCE_RESULT.IMP_ING_PER_ML, 0)) 
	+ sum(nvl(BWHCORE.MS0_FT_DWH_BLCE_RESULT.IMP_ING_CAP_ML, 0)) 
	+ sum(nvl(BWHCORE.MS0_FT_DWH_BLCE_RESULT.IMP_ING_REAJ_ML, 0)) 
	+ sum(nvl(BWHCORE.MS0_FT_DWH_BLCE_RESULT.IMP_EGR_PER_ML, 0)) 
	+ sum(nvl(BWHCORE.MS0_FT_DWH_BLCE_RESULT.IMP_EGR_CAP_ML, 0)) 
	+ sum(nvl(BWHCORE.MS0_FT_DWH_BLCE_RESULT.IMP_EGR_REAJ_ML, 0)) Rof
FROM
	BWHCORE.MS0_FT_DWH_BLCE_RESULT PARTITION (pmes_54_202006),
	BWHCORE.MS0_DM_DWH_AREA_NEGOCIO_CTR PARTITION (PAIS_54),
	BWHCORE.MS0_DM_DWH_CTA_RESULTADOS_CTR PARTITION (PAIS_54),
	BWHCORE.MS0_DM_DWH_PRODUCTOS_CTR PARTITION (PAIS_54)
WHERE
	( BWHCORE.MS0_FT_DWH_BLCE_RESULT.COD_PAIS = BWHCORE.MS0_DM_DWH_CTA_RESULTADOS_CTR.COD_PAIS
	AND BWHCORE.MS0_DM_DWH_CTA_RESULTADOS_CTR.COD_JERQ_CR01 = 'JCNBV'
	AND BWHCORE.MS0_DM_DWH_CTA_RESULTADOS_CTR.COD_CTA_RESULTADOS_NIV_8 = '1052'
	AND BWHCORE.MS0_FT_DWH_BLCE_RESULT.COD_CTA_CONT_GESTION = BWHCORE.MS0_DM_DWH_CTA_RESULTADOS_CTR.COD_CTA_RESULTADOS )
	AND ( BWHCORE.MS0_DM_DWH_AREA_NEGOCIO_CTR.COD_PAIS = BWHCORE.MS0_FT_DWH_BLCE_RESULT.COD_PAIS
	AND BWHCORE.MS0_DM_DWH_AREA_NEGOCIO_CTR.COD_JERQ_ADN01 = 'JAN01'
	AND BWHCORE.MS0_DM_DWH_AREA_NEGOCIO_CTR.COD_AREA_NEGOCIO = BWHCORE.MS0_FT_DWH_BLCE_RESULT.COD_AREA_NEGOCIO )
	AND ( BWHCORE.MS0_FT_DWH_BLCE_RESULT.FEC_DATA = '20200630'
	AND BWHCORE.MS0_FT_DWH_BLCE_RESULT.cod_pais = '54' )
	AND BWHCORE.MS0_DM_DWH_CTA_RESULTADOS_CTR.COD_CTA_RESULTADOS_NIV_6 != '1073'
	AND BWHCORE.MS0_FT_DWH_BLCE_RESULT.IND_POOL = 'N'
	AND BWHCORE.MS0_FT_DWH_BLCE_RESULT.cod_producto_gest = BWHCORE.MS0_DM_DWH_PRODUCTOS_CTR.COD_PRODUCTO 
	AND BWHCORE.MS0_DM_DWH_PRODUCTOS_CTR.COD_PRODUCTO_NIV_3 IN ('BG1','BG2','BG3')
GROUP BY
	BWHCORE.MS0_FT_DWH_BLCE_RESULT.FEC_DATA,
	BWHCORE.MS0_FT_DWH_BLCE_RESULT.COD_CONTENIDO,
	--BWHCORE.MS0_FT_DWH_BLCE_RESULT.COD_AREA_NEGOCIO,
	--BWHCORE.MS0_FT_DWH_BLCE_RESULT.COD_DIVISA,
	--BWHCORE.MS0_DM_DWH_CTA_RESULTADOS_CTR.COD_CTA_RESULTADOS_NIV_7,
	BWHCORE.MS0_DM_DWH_CTA_RESULTADOS_CTR.COD_CTA_RESULTADOS_NIV_8 ,
	BWHCORE.MS0_DM_DWH_PRODUCTOS_CTR.COD_PRODUCTO_NIV_3 ;

-- __/__/__/__/__/__/__/__/__/__/__/__/__/__/__/__/__/__/__/__/__/__/__/__/__ROF_original.

-- COUNT(IDF_CTO_ODS): 1.996.270

  select BWHCORE.MS0_FT_DWH_BLCE_RESULT.FEC_DATA,
  BWHCORE.MS0_FT_DWH_BLCE_RESULT.COD_CONTENIDO,
  BWHCORE.MS0_FT_DWH_BLCE_RESULT.COD_AREA_NEGOCIO,  
  BWHCORE.MS0_FT_DWH_BLCE_RESULT.COD_DIVISA,
  BWHCORE.MS0_DM_DWH_CTA_RESULTADOS_CTR.COD_CTA_RESULTADOS_NIV_7,
  BWHCORE.MS0_DM_DWH_CTA_RESULTADOS_CTR.COD_CTA_RESULTADOS_NIV_8,
  sum(nvl(BWHCORE.MS0_FT_DWH_BLCE_RESULT.IMP_ING_PER_ML,0)) 
  + sum(nvl(BWHCORE.MS0_FT_DWH_BLCE_RESULT.IMP_ING_CAP_ML,0)) 
  + sum(nvl(BWHCORE.MS0_FT_DWH_BLCE_RESULT.IMP_ING_REAJ_ML,0)) 
  + sum(nvl(BWHCORE.MS0_FT_DWH_BLCE_RESULT.IMP_EGR_PER_ML,0)) 
  + sum(nvl(BWHCORE.MS0_FT_DWH_BLCE_RESULT.IMP_EGR_CAP_ML,0))  
  + sum(nvl(BWHCORE.MS0_FT_DWH_BLCE_RESULT.IMP_EGR_REAJ_ML,0))    Rof
  FROM
  BWHCORE.MS0_FT_DWH_BLCE_RESULT partition (pmes_54_202006),
  BWHCORE.MS0_DM_DWH_AREA_NEGOCIO_CTR  PARTITION (PAIS_54),
  BWHCORE.MS0_DM_DWH_CTA_RESULTADOS_CTR   PARTITION (PAIS_54)
  WHERE
     (      BWHCORE.MS0_FT_DWH_BLCE_RESULT.COD_PAIS  = BWHCORE.MS0_DM_DWH_CTA_RESULTADOS_CTR.COD_PAIS  AND
    BWHCORE.MS0_DM_DWH_CTA_RESULTADOS_CTR.COD_JERQ_CR01 = 'JCNBV'  AND
    BWHCORE.MS0_DM_DWH_CTA_RESULTADOS_CTR.COD_CTA_RESULTADOS_NIV_8 = '1052' AND
    BWHCORE.MS0_FT_DWH_BLCE_RESULT.COD_CTA_CONT_GESTION = BWHCORE.MS0_DM_DWH_CTA_RESULTADOS_CTR.COD_CTA_RESULTADOS      )
     AND 
       (  BWHCORE.MS0_DM_DWH_AREA_NEGOCIO_CTR.COD_PAIS = BWHCORE.MS0_FT_DWH_BLCE_RESULT.COD_PAIS   AND
  BWHCORE.MS0_DM_DWH_AREA_NEGOCIO_CTR.COD_JERQ_ADN01 = 'JAN01'   AND
  BWHCORE.MS0_DM_DWH_AREA_NEGOCIO_CTR.COD_AREA_NEGOCIO = BWHCORE.MS0_FT_DWH_BLCE_RESULT.COD_AREA_NEGOCIO )
  AND
  (   BWHCORE.MS0_FT_DWH_BLCE_RESULT.FEC_DATA  =   '20200630'   AND
   BWHCORE.MS0_FT_DWH_BLCE_RESULT.cod_pais  =   '54'           )
GROUP BY
  BWHCORE.MS0_FT_DWH_BLCE_RESULT.FEC_DATA,
  BWHCORE.MS0_FT_DWH_BLCE_RESULT.COD_CONTENIDO,
  BWHCORE.MS0_FT_DWH_BLCE_RESULT.COD_AREA_NEGOCIO,  
  BWHCORE.MS0_FT_DWH_BLCE_RESULT.COD_DIVISA,
  BWHCORE.MS0_DM_DWH_CTA_RESULTADOS_CTR.COD_CTA_RESULTADOS_NIV_7,
  BWHCORE.MS0_DM_DWH_CTA_RESULTADOS_CTR.COD_CTA_RESULTADOS_NIV_8 ;


-- __/__/__/__/__/__/__/__/__/__/__/__/__/__/__/__/__ bt_ror_input_activo

--_c0|_c1       |
-----|----------|
--CRE|         0|
--CCL|94947.7999|
--CTB|40621.6802|
--ROF|         0|

-- ya filtra los contratos que tienen nivel_3 de producto igual a BG1 y BG3.
SELECT SUBSTRING(cod_ren_contrato_rorac,1,3) , SUM(fc_ren_rof)
FROM bi_corp_common.bt_ror_input_activo
WHERE partition_date = '2020-06-30' 
AND SUBSTRING(cod_ren_contrato_rorac,1,3) = IN ('CCL','ROF','CTB','CRE')
GROUP BY SUBSTRING(cod_ren_contrato_rorac,1,3) ;