CREATE EXTERNAL TABLE IF NOT EXISTS bi_corp_common.stk_adm_empresas_estado_origen_aplicacion_fondos (
    id_adm_eoaf int,
    dt_adm_blc string,
    flag_adm_consolidado int,
    cod_adm_penumper int,
    dt_adm_eoaf string,
    fc_adm_deudxvtas decimal(16, 2),
    fc_adm_bscambio decimal(16, 2),
    fc_adm_deucomerci decimal(16, 2),
    fc_adm_deusocyfisc decimal(16, 2),
    fc_adm_deusistfinanc decimal(16, 2),
    fc_adm_inv_actintang decimal(16, 2),
    fc_adm_aportescap decimal(16, 2),
    fc_adm_distresult decimal(16, 2),
    fc_adm_credsocyev decimal(16, 2),
    ds_adm_otr_varcaptr1 string,
    imp_otr_varcaptr1 decimal(16, 2),
    ds_adm_otr_varcaptr2 string,
    imp_otr_varcaptr2 decimal(16, 2),
    ds_adm_otr_varcaptr3 string,
    imp_otr_varcaptr3 decimal(16, 2),
    ds_adm_otr_oanooper1 string,
    ds_adm_otr_oanooper2 string,
    ds_adm_otr_oanooper3 string,
    fc_adm_imp_otr_varcaptr1_ori decimal(16, 2),
    fc_adm_imp_otr_varcaptr2_ori decimal(16, 2),
    fc_adm_imp_otr_varcaptr3_ori decimal(16, 2),
    fc_adm_imp_otr_oanooper1_ori decimal(16, 2),
    fc_adm_imp_otr_oanooper2_ori decimal(16, 2),
    fc_adm_imp_otr_oanooper3_ori decimal(16, 2),
    fc_adm_imp_otr_varcaptr1_apl decimal(16, 2),
    fc_adm_imp_otr_varcaptr2_apl decimal(16, 2),
    fc_adm_imp_otr_varcaptr3_apl decimal(16, 2),
    fc_adm_imp_otr_oanooper1_apl decimal(16, 2),
    fc_adm_imp_otr_oanooper2_apl decimal(16, 2),
    fc_adm_imp_otr_oanooper3_apl decimal(16, 2),
    fc_adm_ingxvtasxperid decimal(16, 2),
    fc_adm_resultposblc decimal(16, 2),
    int_adm_difmeses int,
    cod_adm_peusualt string,
    cod_adm_peusumod string,
    ts_adm_pefecalt string,
    ts_adm_pefecmod string,
    id_adm_blc bigint,
    ds_adm_observaciones string,
    cod_adm_nro_ultima_prop bigint
)
PARTITIONED BY (
  partition_date string)
STORED AS PARQUET
LOCATION
  '${DATA_LAKE_SERVER}/santander/bi-corp/common/admision/stk_adm_empresas_estado_origen_aplicacion_fondos';