INVALIDATE METADATA santander_business_risk_arda.operaciones_bam_rda;
COMPUTE INCREMENTAL STATS santander_business_risk_arda.operaciones_bam_rda;
INVALIDATE METADATA santander_business_risk_arda.operaciones_bam_rda_inconsistencias;
COMPUTE INCREMENTAL STATS santander_business_risk_arda.operaciones_bam_rda_inconsistencias;