INVALIDATE METADATA santander_business_risk_arda.cargabal_rda;
COMPUTE INCREMENTAL STATS santander_business_risk_arda.cargabal_rda;
INVALIDATE METADATA santander_business_risk_arda.cargabal_rda_inconsistencias;
COMPUTE INCREMENTAL STATS santander_business_risk_arda.cargabal_rda_inconsistencias;