INVALIDATE METADATA santander_business_risk_arda.np_seguros_rda;
COMPUTE INCREMENTAL STATS santander_business_risk_arda.np_seguros_rda;
INVALIDATE METADATA santander_business_risk_arda.np_seguros_rda_inconsistencias;
COMPUTE INCREMENTAL STATS santander_business_risk_arda.np_seguros_rda_inconsistencias;