SET mapred.job.queue.name=root.dataeng;
CREATE VIEW IF NOT EXISTS bi_corp_business.vagg_cue_cuentas AS
select cod_per_nup cod_nup,
sum(case when c.cod_cue_estado_cuenta = 'A' and ((flag_cue_paquete =1 and cod_cue_divisa ='ARS') or flag_cue_paquete =0) then 1 else 0 end) as int_cuentas_total,
sum(case when ((flag_cue_paquete =1 and cod_cue_divisa ='ARS') or flag_cue_paquete =0) and cod_cue_producto_actual='70' then 1 else 0 end) as int_cuentas_total_gym,
sum(case when c.cod_cue_estado_cuenta = 'A' and p.bap = '1' and ((flag_cue_paquete =1 and cod_cue_divisa ='ARS') or flag_cue_paquete =0) then 1 else 0 end) as int_BAP,
sum(case when p.bap = '1' and ((flag_cue_paquete =1 and cod_cue_divisa ='ARS') or flag_cue_paquete =0) and cod_cue_producto_actual='70' then 1 else 0 end) as int_BAP_GYM,
sum(case when c.cod_cue_estado_cuenta = 'A' and p.producto_agrup = 'P.Negocio Black' and ((flag_cue_paquete =1 and cod_cue_divisa ='ARS') or flag_cue_paquete =0) then 1 else 0 end) as int_BLACK_BAP,
sum(case when p.producto_agrup = 'P.Negocio Black' and ((flag_cue_paquete =1 and cod_cue_divisa ='ARS') or flag_cue_paquete =0) and cod_cue_producto_actual='70' then 1 else 0 end) as int_BLACK_BAP_GYM,
sum(case when c.cod_cue_estado_cuenta = 'A' and p.producto_agrup = 'Black' and ((flag_cue_paquete =1 and cod_cue_divisa ='ARS') or flag_cue_paquete =0) then 1 else 0 end) as int_BLACK,
sum(case when p.producto_agrup = 'Black' and ((flag_cue_paquete =1 and cod_cue_divisa ='ARS') or flag_cue_paquete =0) and cod_cue_producto_actual='70' then 1 else 0 end) as int_BLACK_GYM,
sum(case when c.cod_cue_estado_cuenta = 'A' and p.producto_agrup = 'P.Negocio Platinum' and ((flag_cue_paquete =1 and cod_cue_divisa ='ARS') or flag_cue_paquete =0) then 1 else 0 end) as int_PLATINUM_BAP,
sum(case when p.producto_agrup = 'P.Negocio Platinum' and ((flag_cue_paquete =1 and cod_cue_divisa ='ARS') or flag_cue_paquete =0) and cod_cue_producto_actual='70' then 1 else 0 end) as int_PLATINUM_BAP_GYM,
sum(case when c.cod_cue_estado_cuenta = 'A' and p.producto_agrup = 'Platinum' and ((flag_cue_paquete =1 and cod_cue_divisa ='ARS') or flag_cue_paquete =0) then 1 else 0 end) as int_PLATINUM,
sum(case when p.producto_agrup = 'Platinum' and ((flag_cue_paquete =1 and cod_cue_divisa ='ARS') or flag_cue_paquete =0) and cod_cue_producto_actual='70' then 1 else 0 end) as int_PLATINUM_GYM,
sum(case when c.cod_cue_estado_cuenta = 'A' and p.producto_agrup = 'P.Negocio Gold' and ((flag_cue_paquete =1 and cod_cue_divisa ='ARS') or flag_cue_paquete =0) then 1 else 0 end) as int_GOLD_BAP,
sum(case when p.producto_agrup = 'P.Negocio Gold' and ((flag_cue_paquete =1 and cod_cue_divisa ='ARS') or flag_cue_paquete =0) and cod_cue_producto_actual='70' then 1 else 0 end) as int_GOLD_BAP_GYM,
sum(case when c.cod_cue_estado_cuenta = 'A' and p.producto_agrup = 'Gold' and ((flag_cue_paquete =1 and cod_cue_divisa ='ARS') or flag_cue_paquete =0) then 1 else 0 end) as int_GOLD,
sum(case when p.producto_agrup = 'Gold' and ((flag_cue_paquete =1 and cod_cue_divisa ='ARS') or flag_cue_paquete =0) and cod_cue_producto_actual='70' then 1 else 0 end) as int_GOLD_GYM,
sum(case when c.cod_cue_estado_cuenta = 'A' and p.producto_agrup = 'P.Negocio' and ((flag_cue_paquete =1 and cod_cue_divisa ='ARS') or flag_cue_paquete =0) then 1 else 0 end) as int_UNO_BAP,
sum(case when p.producto_agrup = 'P.Negocio' and ((flag_cue_paquete =1 and cod_cue_divisa ='ARS') or flag_cue_paquete =0) and cod_cue_producto_actual='70' then 1 else 0 end) as int_UNO_BAP_GYM,
sum(case when c.cod_cue_estado_cuenta = 'A' and p.producto_agrup = 'Uno' and ((flag_cue_paquete =1 and cod_cue_divisa ='ARS') or flag_cue_paquete =0) then 1 else 0 end) as int_UNO,
sum(case when p.producto_agrup = 'Uno' and ((flag_cue_paquete =1 and cod_cue_divisa ='ARS') or flag_cue_paquete =0) and cod_cue_producto_actual='70' then 1 else 0 end) as int_UNO_GYM,
sum(case when c.cod_cue_estado_cuenta = 'A' and p.producto_agrup = 'Super Cta 3' and ((flag_cue_paquete =1 and cod_cue_divisa ='ARS') or flag_cue_paquete =0) then 1 else 0 end) as int_SC3,
sum(case when p.producto_agrup = 'Super Cta 3' and ((flag_cue_paquete =1 and cod_cue_divisa ='ARS') or flag_cue_paquete =0) and cod_cue_producto_actual='70' then 1 else 0 end) as int_SC3_GYM,
sum(case when c.cod_cue_estado_cuenta = 'A' and p.producto_agrup = 'Super Cta 2' and ((flag_cue_paquete =1 and cod_cue_divisa ='ARS') or flag_cue_paquete =0) then 1 else 0 end) as int_SC2,
sum(case when p.producto_agrup = 'Super Cta 2' and ((flag_cue_paquete =1 and cod_cue_divisa ='ARS') or flag_cue_paquete =0) and cod_cue_producto_actual='70' then 1 else 0 end) as int_SC2_GYM,
sum(case when c.cod_cue_estado_cuenta = 'A' and p.producto_agrup in ('Super Cta Negocio con PPP','Super Cta Negocio') and ((flag_cue_paquete =1 and cod_cue_divisa ='ARS') or flag_cue_paquete =0) then 1 else 0 end) as int_SC1_BAP,
sum(case when p.producto_agrup in ('Super Cta Negocio con PPP','Super Cta Negocio') and cod_cue_producto_actual='70' then 1 else 0 end) as int_SC1_BAP_GYM,
sum(case when c.cod_cue_estado_cuenta = 'A' and p.producto_agrup = 'Super Cta 1' and ((flag_cue_paquete =1 and cod_cue_divisa ='ARS') or flag_cue_paquete =0) then 1 else 0 end) as int_SC1,
sum(case when p.producto_agrup = 'Super Cta 1' and ((flag_cue_paquete =1 and cod_cue_divisa ='ARS') or flag_cue_paquete =0) and cod_cue_producto_actual='70' then 1 else 0 end) as int_SC1_GYM,
sum(case when c.cod_cue_estado_cuenta = 'A' and p.producto_agrup in ('Cta Cte','Cta Cte Dol') and ((flag_cue_paquete =1 and cod_cue_divisa ='ARS') or flag_cue_paquete =0) then 1 else 0 end) as int_CC,
sum(case when p.producto_agrup in ('Cta Cte','Cta Cte Dol') and ((flag_cue_paquete =1 and cod_cue_divisa ='ARS') or flag_cue_paquete =0) and cod_cue_producto_actual='70' then 1 else 0 end) as int_CC_GYM,
sum(case when c.cod_cue_estado_cuenta = 'A' and p.producto_agrup = 'Super Cta 1 PPP' and ((flag_cue_paquete =1 and cod_cue_divisa ='ARS') or flag_cue_paquete =0) then 1 else 0 end) as int_SPRE,
sum(case when p.producto_agrup = 'Super Cta 1 PPP' and ((flag_cue_paquete =1 and cod_cue_divisa ='ARS') or flag_cue_paquete =0) and cod_cue_producto_actual='70' then 1 else 0 end) as int_SPRE_GYM,
sum(case when c.cod_cue_estado_cuenta = 'A' and p.producto_agrup = 'Super Cta 1 PAS' and c.dt_cue_primer_movimiento_genuino is not null and ((flag_cue_paquete =1 and cod_cue_divisa ='ARS') or flag_cue_paquete =0) then 1 else 0 end) as int_RIOPERS,
sum(case when p.producto_agrup = 'Super Cta 1 PAS' and c.dt_cue_primer_movimiento_genuino is not null and ((flag_cue_paquete =1 and cod_cue_divisa ='ARS') or flag_cue_paquete =0) and cod_cue_producto_actual='70' then 1 else 0 end) as int_RIOPERS_GYM,
sum(case when c.cod_cue_estado_cuenta = 'A' and p.producto_agrup = 'Super Cta 1 PAS' and c.dt_cue_primer_movimiento_genuino is null and ((flag_cue_paquete =1 and cod_cue_divisa ='ARS') or flag_cue_paquete =0) then 1 else 0 end) as int_RIOPERS_SIN_MOV,
sum(case when p.producto_agrup = 'Super Cta 1 PAS' and c.dt_cue_primer_movimiento_genuino is null and ((flag_cue_paquete =1 and cod_cue_divisa ='ARS') or flag_cue_paquete =0) and cod_cue_producto_actual='70' then 1 else 0 end) as int_RIOPERS_SIN_MOV_GYM,
sum(case when c.cod_cue_estado_cuenta = 'A' and p.producto_agrup = 'Super Cta 1 Uni' and ((flag_cue_paquete =1 and cod_cue_divisa ='ARS') or flag_cue_paquete =0) then 1 else 0 end) as int_SC1_UNIVERSIA,
sum(case when p.producto_agrup = 'Super Cta 1 Uni' and ((flag_cue_paquete =1 and cod_cue_divisa ='ARS') or flag_cue_paquete =0) and cod_cue_producto_actual='70' then 1 else 0 end) as int_SC1_UNIVERSIA_GYM,
sum(case when c.cod_cue_estado_cuenta = 'A' and p.producto_agrup in ('C Ahorro','C Ahorro AUH','C Ahorro Dol','Fdo Desemp') and ((flag_cue_paquete =1 and cod_cue_divisa ='ARS') or flag_cue_paquete =0) then 1 else 0 end) as int_CA,
sum(case when p.producto_agrup in ('C Ahorro','C Ahorro AUH','C Ahorro Dol','Fdo Desemp') and ((flag_cue_paquete =1 and cod_cue_divisa ='ARS') or flag_cue_paquete =0) and cod_cue_producto_actual='70' then 1 else 0 end) as int_CA_GYM,
sum(case when c.cod_cue_estado_cuenta = 'A' and p.producto_agrup = 'Super Cta BP' and ((flag_cue_paquete =1 and cod_cue_divisa ='ARS') or flag_cue_paquete =0) then 1 else 0 end) as int_CTA_BP,
sum(case when p.producto_agrup = 'Super Cta BP' and ((flag_cue_paquete =1 and cod_cue_divisa ='ARS') or flag_cue_paquete =0) and cod_cue_producto_actual='70' then 1 else 0 end) as int_CTA_BP_GYM,
sum(case when c.cod_cue_estado_cuenta = 'A' and p.producto_agrup = 'Cta Pyme' and ((flag_cue_paquete =1 and cod_cue_divisa ='ARS') or flag_cue_paquete =0) then 1 else 0 end) as int_CTA_PYM,
sum(case when p.producto_agrup = 'Cta Pyme' and ((flag_cue_paquete =1 and cod_cue_divisa ='ARS') or flag_cue_paquete =0) and cod_cue_producto_actual='70' then 1 else 0 end) as int_CTA_PYM_GYM,
sum(case when c.cod_cue_estado_cuenta = 'A' and p.producto_agrup = 'Cta Instituciones' and ((flag_cue_paquete =1 and cod_cue_divisa ='ARS') or flag_cue_paquete =0) then 1 else 0 end) as int_CTA_INST,
sum(case when p.producto_agrup = 'Cta Instituciones' and ((flag_cue_paquete =1 and cod_cue_divisa ='ARS') or flag_cue_paquete =0) and cod_cue_producto_actual='70' then 1 else 0 end) as int_CTA_INST_GYM,
sum(case when c.cod_cue_estado_cuenta = 'A' and p.producto_agrup in ('Empresas','Empresas P2') and ((flag_cue_paquete =1 and cod_cue_divisa ='ARS') or flag_cue_paquete =0) then 1 else 0 end) as int_RIO_EMP,
sum(case when p.producto_agrup in ('Empresas','Empresas P2') and ((flag_cue_paquete =1 and cod_cue_divisa ='ARS') or flag_cue_paquete =0) and cod_cue_producto_actual='70' then 1 else 0 end) as int_RIO_EMP_GYM,
sum(case when c.cod_cue_estado_cuenta = 'A' and p.producto_agrup like 'Super Pack%' and ((flag_cue_paquete =1 and cod_cue_divisa ='ARS') or flag_cue_paquete =0) then 1 else 0 end) as int_SUPER_PACK,
sum(case when p.producto_agrup like 'Super Pack%' and ((flag_cue_paquete =1 and cod_cue_divisa ='ARS') or flag_cue_paquete =0) and cod_cue_producto_actual='70' then 1 else 0 end) as int_SUPER_PACK_GYM,
sum(case when c.cod_cue_estado_cuenta = 'A' and p.producto_agrup = 'Cta Agro' and ((flag_cue_paquete =1 and cod_cue_divisa ='ARS') or flag_cue_paquete =0) then 1 else 0 end) as int_CTA_AGRO,
sum(case when producto_agrup = 'Cta Agro' and ((flag_cue_paquete =1 and cod_cue_divisa ='ARS') or flag_cue_paquete =0) and cod_cue_producto_actual='70' then 1 else 0 end) as int_CTA_AGRO_GYM,
sum(case when c.cod_cue_estado_cuenta = 'A' and p.producto_agrup = 'Cta Consorcio' and ((flag_cue_paquete =1 and cod_cue_divisa ='ARS') or flag_cue_paquete =0) then 1 else 0 end) as int_CTA_CONS,
sum(case when p.producto_agrup = 'Cta Consorcio' and ((flag_cue_paquete =1 and cod_cue_divisa ='ARS') or flag_cue_paquete =0) and cod_cue_producto_actual='70' then 1 else 0 end) as int_CTA_CONS_GYM,
sum(case when c.cod_cue_estado_cuenta = 'A' and p.producto_agrup = 'Cta Comercio' and ((flag_cue_paquete =1 and cod_cue_divisa ='ARS') or flag_cue_paquete =0) then 1 else 0 end) as int_CTA_COM,
sum(case when p.producto_agrup = 'Cta Comercio' and ((flag_cue_paquete =1 and cod_cue_divisa ='ARS') or flag_cue_paquete =0) and cod_cue_producto_actual='70' then 1 else 0 end) as int_CTA_COM_GYM,
sum(case when c.cod_cue_estado_cuenta = 'A' and p.producto_agrup = 'Cuenta Interna' and ((flag_cue_paquete =1 and cod_cue_divisa ='ARS') or flag_cue_paquete =0) then 1 else 0 end) as int_CTA_INTERNA,
sum(case when p.producto_agrup = 'Cuenta Interna' and ((flag_cue_paquete =1 and cod_cue_divisa ='ARS') or flag_cue_paquete =0) and cod_cue_producto_actual='70' then 1 else 0 end) as int_CTA_INTERNA_GYM,
sum(case when c.cod_cue_estado_cuenta = 'A' and c.cod_cue_divisa = 'ARS' then fc_cue_saldo_dispuesto end) as fc_saldo_pesos,
sum(case when c.cod_cue_estado_cuenta = 'A' and c.cod_cue_divisa = 'ARS' and fc_cue_saldo_dispuesto >0 then fc_cue_saldo_dispuesto else 0 end) as fc_saldo_vista_pesos,
sum(case when c.cod_cue_estado_cuenta = 'A' and c.cod_cue_divisa = 'USD' then fc_cue_saldo_dispuesto end) as fc_saldo_dolares,
sum(case when c.cod_cue_estado_cuenta = 'A' and c.cod_cue_divisa = 'USD' and fc_cue_saldo_dispuesto >0 then fc_cue_saldo_dispuesto else 0 end) as fc_saldo_vista_dolares,
max(fc_cue_disponible_total_acuerdos) fc_descubierto_acuerdo,
max(coalesce(fc_cue_monto_acuerdo_comun,0)) fc_descubierto_usado,
partition_date
from bi_corp_common.stk_cue_cuentas c
left join bi_corp_staging.exa_dim_productos p on
        coalesce(c.cod_cue_producto_paquete, c.cod_cue_producto) = p.producto
        and coalesce(c.cod_cue_subroducto_paquete, c.cod_cue_subproducto) = p.subproducto
INNER JOIN (select max(partition_date) as max from bi_corp_staging.exa_dim_productos where partition_date >= date_sub(to_date(from_unixtime(unix_timestamp())),7) ) m on p.partition_date = m.max
 where c.partition_date='2019-06-19' -- hay que sacar este filtro ya que se va a filtrar al consultar la vista
 and p.partition_date > date_sub(to_date(from_unixtime(unix_timestamp())),7) --toma la particion mas reciente de productos
 and not (cod_cue_producto = '02' and cod_cue_subproducto = '0018')
 group by cod_per_nup;