create table capital.rwa_final_envio (
periodo numeric(8,0),
nup varchar ,
sucursal_cliente varchar ,
stage int ,
segmento varchar ,
ead_stage_1 numeric(18,2) ,
ead_stage_2 numeric(18,2) ,
ead_stage_3 numeric(18,2) ,
ead numeric(18,2) ,
insolvencias_stage_1 numeric(18,2) ,
insolvencias_stage_2 numeric(18,2) ,
insolvencias_stage_3 numeric(18,2) ,
rwa numeric(18,2) ,
rwa_neteados_negativos numeric(38,2) ,
rw numeric(38,2) ,
flag_factor_corrector int ,
facturacion_en_euros numeric(38,2) ,
flag_sblc_avales int ,
flag_hipotecas_comerciales int ,
agregado_faltante_insolvencia int ,
agregado_faltante_offshore int );