CREATE TABLE CNL01.AGRUPAMIENTO (
	COD_SECTOR VARCHAR2(2),
	CANAL_ID VARCHAR2(5),
	TX_ID VARCHAR2(6),
	ENTE_ID VARCHAR2(3),
	COD_GRUPO VARCHAR2(4),
	INFORMA_MARCA VARCHAR2(1),
	FECHA_INFORMA DATE
); 
